export const categories = [
  {slug:'kuruyemis-kavurma-makineleri',name:'Kuruyemiş Kavurma Makineleri',short:'Bantlı kavurma ve kurutma hatları',intro:'Kuruyemiş kavurma makinesi ve bantlı kavurma fırını seçeneklerini; fıstık kavurma fırını ve leblebi kavurma ihtiyaçlarını, hat akışı ve kapasiteye göre değerlendirin. Otomatik tuzlama uygulamasını sonraki üretim adımıyla birlikte planlayın. İkinci el kavurma makinesi arıyorsanız güncel model ve bulunabilirlik bilgisini ekibimizden teyit edin; ikinci el seçenekler yalnızca kavurma makineleri için değerlendirilir.'},
  {slug:'kilavuzlu-kavurma-makineleri',name:'Kılavuzlu Kavurma Makineleri',short:'Dönerli kavurma sistemleri',intro:'Dönerli kavurma makinesi arayan işletmeler için kılavuzlu ve parti tipi fırın seçenekleri; ürün, parti büyüklüğü ve tesis yerleşimine göre karşılaştırılır.'},
  {slug:'kuruyemis-tuzlama-ekipmanlari',name:'Kuruyemiş Tuzlama Ekipmanları',short:'Kaplama ve tatlandırma aşaması',intro:'Kavurma sonrası ürünün tuz ve baharatla homojen buluşmasına yönelik ekipmanlar.'},
  {slug:'kahve-kavurma-makineleri',name:'Kahve Kavurma Makineleri',short:'Kahve çekirdeği için kavurma',intro:'Kahve üretim akışına uygun kavurma makinesi seçenekleri.'},
  {slug:'isitma-yakit-sistemleri',name:'Isıtma ve Yakıt Sistemleri',short:'Hatlara uyumlu ısı çözümleri',intro:'Kavurma hatlarında ısı ihtiyacına göre değerlendirilen yardımcı sistemler.'},
  {slug:'kuruyemis-paketleme-makineleri',name:'Kuruyemiş Paketleme Makineleri',short:'Üretimden paketlemeye',intro:'Kavurma ve işleme sonrasında paketleme aşamasına yönelik makine çözümleri.'},
  {slug:'elekler',name:'Elekler',short:'Ayırma ve sınıflandırma',intro:'Ay çekirdeği eleği ve kuruyemiş eleme çözümlerini ürün boyutu, ayırma hedefi ve hat kapasitesine göre inceleyin; ayıklama konveyörü ve seçme bandı uygulamalarını da karşılaştırın.'},
  {slug:'leblebi-kizartma-makineleri',name:'Leblebi Kızartma Makineleri',short:'Leblebi üretimine özel',intro:'Leblebi işleme ve kızartma süreçlerine yönelik makine seçenekleri.'},
  {slug:'cekmeli-kuruyemis-firinlari',name:'Çekmeli Kuruyemiş Fırınları',short:'Tepsili fırın çözümleri',intro:'Katlı kurutma fırını ve çekmeceli kuruyemiş fırını aramalarında; tepsi düzeni, kurutulacak ürün ve tesis kapasitesi birlikte değerlendirilmelidir. Meyve-sebze kurutma ihtiyacının makine uygunluğunu üreticiyle ayrıca teyit edin.'},
  {slug:'leblebi-seker-makineleri',name:'Leblebi Şeker Makineleri',short:'Şekerleme ekipmanları',intro:'Leblebi şekerleme aşamasında kullanılan makineler.'},
  {slug:'sari-leblebi-imalat-makineleri',name:'Sarı Leblebi İmalat Makineleri',short:'İmalat hattı ekipmanları',intro:'Sarı leblebi üretiminin işlem adımlarına yönelik makine seçenekleri.'},
  {slug:'secme-bantlari',name:'Seçme Bantları',short:'Görsel kalite kontrol',intro:'Kuruyemiş seçme bandı ve ayıklama konveyörü seçenekleri; ürün akışı, operatör sayısı, ayıklama adımı ve mevcut eleme hattıyla uyuma göre değerlendirilir.'},
  {slug:'draje-kaplama-makineleri',name:'Draje Kaplama Makineleri',short:'Kaplama prosesleri',intro:'Kuruyemiş ve şekerleme ürünlerinde draje kaplama için makine seçenekleri.'},
  {slug:'fritoz-cips-uretim-makineleri',name:'Fritöz ve Cips Üretim Makineleri',short:'Kızartma üretim hattı',intro:'Cips ve benzeri ürünlerin kızartma aşamasına yönelik ekipmanlar.'}
];

const roast='kuruyemis-kavurma-makineleri';
export const products = [
  {model:'HT 15',slug:'ht-15-kuruyemis-kavurma-makinesi',name:'HT 15 Kuruyemiş Kavurma Makinesi',category:roast,summary:'Kompakt ölçekte kuruyemiş kavurma için HT serisi model.',image:'ht-15.webp'},
  {model:'HT 30',slug:'ht-30-kuruyemis-kavurma-makinesi',name:'HT 30 Kuruyemiş Kavurma Makinesi',category:roast,summary:'Kuruyemiş kavurma üretim hattı için HT serisi model.',image:'ht-30.webp'},
  {model:'HT 75',slug:'ht-75-kuruyemis-kavurma-makinesi',name:'HT 75 Kuruyemiş Kavurma Makinesi',category:roast,summary:'Kuruyemiş kavurma ve proses planlamasında değerlendirilebilen HT serisi model.',image:'ht-75.webp'},
  {model:'HT 150',slug:'ht-150-kavurma-kurutma-makinesi',name:'HT 150 Kavurma ve Kurutma Makinesi',category:roast,summary:'Kavurma ve kurutma prosesleri için HT serisi makine.',image:'ht-150.webp',specs:[['Uzunluk','3350 mm'],['Genişlik','1800 mm'],['Yükseklik','2250 mm']]},
  {model:'HT 500',slug:'ht-500-kavurma-kurutma-makinesi',name:'HT 500 Kavurma ve Kurutma Makinesi',category:roast,summary:'Kavurma ve kurutma hatlarında kullanılan HT serisi model.',image:'ht-500.webp'},
  {model:'HT 750',slug:'ht-750-kuruyemis-kavurma-makinesi',name:'HT 750 Kuruyemiş Kavurma Makinesi',category:roast,summary:'Yüksek hacimli üretim planları için HT serisi kavurma makinesi.',image:'ht-750.webp'},
  {model:'HT 1000',slug:'ht-1000-kuruyemis-kavurma-makinesi',name:'HT 1000 Kuruyemiş Kavurma Makinesi',category:roast,summary:'Büyük ölçekli kuruyemiş kavurma hatları için HT serisi model.',image:'ht-1000.webp'},
  {model:'Leblebi Kavurma',slug:'leblebi-kavurma-makinesi',name:'Leblebi Kavurma Makinesi',category:'leblebi-kizartma-makineleri',summary:'Leblebi kavurma ve işleme hattına yönelik makine grubu.',image:'leblebi-kavurma-makinesi.webp'},
  {model:'HT 30',slug:'ht-30-kahve-kavurma-makinesi',name:'HT 30 Kahve Kavurma Makinesi',category:'kahve-kavurma-makineleri',summary:'Kahve çekirdeği kavurma için HT 30 modeli.',image:'ht-30-kahve.webp'},
  {model:'HT 100',slug:'ht-100-kilavuzlu-kavurma-firini',name:'HT 100 Kılavuzlu Kavurma Fırını',category:'kilavuzlu-kavurma-makineleri',summary:'Kılavuzlu kavurma fırınları arasında HT 100 modeli.',image:'ht-100-kilavuzlu-kavurma-firini.webp'},
  {model:'HT 120',slug:'ht-120-kilavuzlu-kavurma-firini',name:'HT 120 Kılavuzlu Kavurma Fırını',category:'kilavuzlu-kavurma-makineleri',summary:'Parti bazlı kavurma planlarında değerlendirilen HT 120 modeli.',image:'ht-120-kilavuzlu-kavurma-firini.webp'},
  {model:'HT 130',slug:'ht-130-kilavuzlu-kavurma-firini',name:'HT 130 Kılavuzlu Kavurma Fırını',category:'kilavuzlu-kavurma-makineleri',summary:'Kılavuzlu kavurma serisindeki HT 130 fırın modeli.',image:'ht-130-kilavuzlu-kavurma-firini.webp'},
  {model:'HT 150',slug:'ht-150-kilavuzlu-kavurma-firini',name:'HT 150 Kılavuzlu Kavurma Fırını',category:'kilavuzlu-kavurma-makineleri',summary:'Kılavuzlu kavurma fırınları arasında HT 150 modeli.',image:'ht-150-kilavuzlu-kavurma-firini.webp'},
  {model:'HT Manuel',slug:'ht-manuel-tuzlama-makinesi',name:'HT Manuel Tuzlama Makinesi',category:'kuruyemis-tuzlama-ekipmanlari',summary:'Kavurma sonrası manuel tuzlama aşamasına yönelik makine.',image:'ht-manuel-tuzlama-makinesi.webp'},
  {model:'Prina Yakıt',slug:'prina-yakit-makinesi',name:'Prina Yakıt Makinesi',category:'isitma-yakit-sistemleri',summary:'Isıtma ve yakıt sistemleri grubundaki prina yakıt makinesi.',image:'prina-yakit-makinesi.webp'},
  {model:'2 Kefeli',slug:'iki-kefeli-yari-otomatik-dolum-sistemi',name:'2 Kefeli Yarı Otomatik Dolum Sistemi',category:'kuruyemis-paketleme-makineleri',summary:'İki kefeli yarı otomatik dolum düzeni için makine.',image:'iki-kefeli-yari-otomatik-dolum-sistemi.webp'},
  {model:'4 Kefeli',slug:'dort-kefeli-yari-otomatik-dolum-makinesi',name:'4 Kefeli Yarı Otomatik Dolum Makinesi',category:'kuruyemis-paketleme-makineleri',summary:'Dört kefeli yarı otomatik dolum makinesi.',image:'dort-kefeli-yari-otomatik-dolum-makinesi.webp'},
  {model:'4 Kefeli',slug:'dort-kefeli-otomatik-paketleme-makinesi',name:'4 Kefeli Otomatik Kuruyemiş Paketleme Makinesi',category:'kuruyemis-paketleme-makineleri',summary:'Dört kefeli otomatik kuruyemiş paketleme modeli.',image:'dort-kefeli-otomatik-paketleme-makinesi.webp'},
  {model:'5 Kefeli',slug:'bes-kefeli-otomatik-paketleme-makinesi',name:'5 Kefeli Otomatik Kuruyemiş Paketleme Makinesi',category:'kuruyemis-paketleme-makineleri',summary:'Beş kefeli otomatik kuruyemiş paketleme modeli.',image:'bes-kefeli-otomatik-paketleme-makinesi.webp'},
  {model:'Elek',slug:'elek',name:'Kuruyemiş Eleği',category:'elekler',summary:'Kuruyemiş işleme hattında eleme ve sınıflandırma için ekipman.',image:'elek.webp'},
  {model:'14 Çekmeceli',slug:'on-dort-cekmeceli-kuruyemis-firini',name:'14 Çekmeceli Kuruyemiş Fırını',category:'cekmeli-kuruyemis-firinlari',summary:'Çekmeli fırın grubunda 14 çekmeceli seçenek.',image:'on-dort-cekmeceli-kuruyemis-firini.webp'},
  {model:'7 Çekmeceli',slug:'yedi-cekmeceli-kuruyemis-firini',name:'7 Çekmeceli Kuruyemiş Fırını',category:'cekmeli-kuruyemis-firinlari',summary:'Çekmeli fırın grubunda 7 çekmeceli seçenek.',image:'yedi-cekmeceli-kuruyemis-firini.webp'},
  {model:'Nohut Sulama',slug:'nohut-sulama-makinesi',name:'Nohut Sulama Makinesi',category:'leblebi-seker-makineleri',summary:'Leblebi işleme hattında nohut sulama aşamasına yönelik makine.',image:'nohut-sulama-makinesi.webp'},
  {model:'Bandırma Nohut',slug:'bandirma-nohut-makinesi',name:'Bandırma Nohut Makinesi',category:'leblebi-seker-makineleri',summary:'Nohut işleme ve bandırma aşaması için makine.',image:'bandirma-nohut-makinesi.webp'},
  {model:'Bakır Çift Kazan',slug:'draje-bakir-cift-kazan',name:'Draje Bakır Çift Kazan',category:'leblebi-seker-makineleri',summary:'Draje üretiminde kullanılan bakır çift kazan seçeneği.',image:'draje-bakir-cift-kazan.webp'},
  {model:'Krom Çift Kazan',slug:'draje-krom-cift-kazan',name:'Draje Krom Çift Kazan',category:'leblebi-seker-makineleri',summary:'Draje üretiminde kullanılan krom çift kazan seçeneği.',image:'draje-krom-cift-kazan.webp'},
  {model:'Krom Tek Kazan',slug:'draje-krom-tek-kazan',name:'Draje Krom Tek Kazan',category:'leblebi-seker-makineleri',summary:'Draje üretiminde kullanılan krom tek kazan seçeneği.',image:'draje-krom-tek-kazan.webp'},
  {model:'Sarı Nohut',slug:'sari-nohut-yapma-makinesi',name:'Sarı Nohut Yapma Makinesi',category:'sari-leblebi-imalat-makineleri',summary:'Sarı leblebi imalatı grubundaki nohut işleme makinesi.',image:'sari-nohut-yapma-makinesi.webp'},
  {model:'Nohut Isıtma',slug:'nohut-isitma-makinesi',name:'Nohut Isıtma Makinesi',category:'sari-leblebi-imalat-makineleri',summary:'Sarı leblebi üretiminde nohut ısıtma aşamasına yönelik makine.',image:'nohut-isitma-makinesi.webp'},
  {model:'Seçme Bandı',slug:'secme-bandi',name:'Kuruyemiş Seçme Bandı',category:'secme-bantlari',summary:'Ürün ayıklama ve seçme akışında kullanılan bant sistemi.',image:'secme-bandi.webp'},
  {model:'Draje Kaplama',slug:'draje-kaplama-sistemi',name:'Draje Kaplama Makinesi',category:'draje-kaplama-makineleri',summary:'Draje kaplama makineleri grubundaki üretim çözümü.',image:'draje-kaplama-sistemi.webp'},
  {model:'Fritöz ve Cips',slug:'fritoz-cips-uretim-sistemi',name:'Fritöz ve Cips Üretim Makinesi',category:'fritoz-cips-uretim-makineleri',summary:'Cips ve benzeri ürünlerin kızartma aşamasına yönelik makine çözümü.',image:'fritoz-cips-uretim-sistemi.webp'}
];

export const articles = [
  {slug:'kuruyemis-kavurma-makinesi-secimi',title:'Kuruyemiş kavurma makinesi seçerken hangi soruları sormalısınız?',desc:'Üründen hedef kapasiteye, yerleşimden servis planına kadar makine görüşmesinde netleştirilmesi gereken başlıklar.',date:'2026-09-23',sections:[['Önce ürünü ve akışı tanımlayın','Fındık, badem, kaju ve yer fıstığı aynı başlangıç koşullarına sahip değildir. Ürünün nemi, boyut dağılımı ve hedef kavurma profili makine seçimini etkiler. Tek bir katalog rakamına bakmadan önce hangi ürünü, hangi reçeteyle işleyeceğinizi yazın.'],['Kapasiteyi gerçek üretim planıyla konuşun','Saatlik hedef kadar vardiya süresi, ürün değişimi ve temizlik araları da önemlidir. Nominal kapasitenin hangi üründe ve hangi şartlarda ölçüldüğünü üreticiden isteyin.'],['Hat yerleşimi ve destek','Besleme, kavurma, soğutma, eleme ve paketleme adımlarını birlikte düşünün. Alan ölçülerini, enerji altyapısını ve servis erişimini teklif aşamasında paylaşın.']]},
  {slug:'kavurma-ve-kurutma-arasindaki-fark',title:'Kavurma ve kurutma: üretim hattında iki ayrı hedef',desc:'Nem yönetimi ve tat geliştirme süreçlerini ayırarak doğru proses sorularını sormaya yardımcı olan kısa rehber.',date:'2026-09-23',sections:[['Kurutmanın amacı','Kurutma, üründeki nemi hedeflenen aralığa çekmek için planlanır. Başlangıç nemi ve son ürün beklentisi proses ayarlarını belirler.'],['Kavurmanın amacı','Kavurma, ısı etkisiyle ürünün tat, koku ve renk profilini oluşturur. Aynı makinede iki işlem yapılabilse de reçete hedefleri ayrı değerlendirilmelidir.'],['Deneme üretimi isteyin','Ticari karar öncesinde kendi hammaddenizle deneme yapıp sonuçları kaydedin. Ürün kalitesini süre, sıcaklık ve son nem gibi ölçümlerle birlikte değerlendirin.']]},
  {slug:'kuruyemis-uretim-hatti-planlama',title:'Kuruyemiş üretim hattı nasıl planlanır?',desc:'Beslemeden paketlemeye ekipman sıralaması, alan ihtiyacı ve işletme akışı üzerine pratik bir başlangıç.',date:'2026-09-23',sections:[['Hammadde girişinden başlayın','Giriş kalitesi, depolama ve besleme biçimi hattın geri kalanını etkiler. Eleme ve ayıklama ihtiyacını ilk aşamada belirleyin.'],['Darboğazı bulun','Kavurma makinesinin kapasitesi tek başına toplam hat kapasitesini belirlemez. Soğutma, seçme, tuzlama ve paketleme adımlarının hızlarını birlikte değerlendirin.'],['Ölçeklenebilir yerleşim','Bakım ve temizlik için erişim alanı bırakın. Gelecekte eklemek isteyeceğiniz ekipman ve ürün çeşitlerini yerleşim planına dahil edin.']]}
];
