import fs from 'node:fs';
import path from 'node:path';
import { localizedGuides } from './localized-guides.mjs';
import {catalogTables,productCatalogSpecs} from './catalog-specs.mjs';
import {guideImage} from './seo-content.mjs';

const site='https://www.sonsuzmakina.com';
const labels={
 en:{lang:'English',dir:'ltr',locale:'en_US',home:'Home',machines:'Machines',about:'About us',gallery:'Gallery',catalog:'E-catalog',guides:'Knowledge center',contact:'Contact',talk:'Discuss your project',discover:'Explore our machines',all:'All machines',details:'View details',group:'Product group',model:'Model',request:'Request information',intro:'Industrial food processing machinery, planned around your product and production goals.',footer:'Let’s plan the next step in your production.',desc:'Sonsuz Makina designs and supplies machinery for nut roasting, drying, coating, sorting and packing. Contact our Denizli team to discuss your product, desired process and plant requirements.',process:'A practical guide to machinery selection and production planning. Confirm current specifications, machine availability and suitability with our team before making an investment decision.',address:'Food and Wholesale Market, 7133 Street, No. 5, Bozburun Neighborhood, Merkezefendi, Denizli, Türkiye',phone:'Phone',email:'Email',social:'Follow Sonsuz Makina',skip:'Skip to content',faq:'What to consider',check:'Define the product and target output, review the complete production flow, and confirm technical requirements using a current product sheet and a sample trial.',ask:'Talk to our team about your product and production plan.',models:'Browse models',latest:'Ask us for current model and availability information.'},
 ar:{lang:'العربية',dir:'rtl',locale:'ar',home:'الرئيسية',machines:'الآلات',about:'من نحن',gallery:'المعرض',catalog:'الكتالوج',guides:'مركز المعرفة',contact:'اتصل بنا',talk:'ناقش مشروعك',discover:'اكتشف آلاتنا',all:'جميع الآلات',details:'التفاصيل',group:'فئة المنتج',model:'الطراز',request:'اطلب معلومات',intro:'آلات صناعية لتجهيز الأغذية، تُختار بما يتناسب مع منتجك وأهداف الإنتاج.',footer:'لنخطط للخطوة التالية في إنتاجك.',desc:'تقدم سونوز ماكينة حلولاً لآلات تحميص المكسرات وتجفيفها وتغطيتها وفرزها وتعبئتها. تواصل مع فريقنا في دنيزلي لمناقشة المنتج والطاقة الإنتاجية ومتطلبات خط الإنتاج.',process:'دليل عملي لاختيار الآلات وتخطيط الإنتاج. يرجى تأكيد المواصفات الحالية وتوفر الآلة ومدى ملاءمتها مع فريقنا قبل اتخاذ قرار الشراء.',address:'موقع تجار الأغذية والجملة، شارع 7133، رقم 5، حي بوزبورون، مركز أفندي، دنيزلي، تركيا',phone:'الهاتف',email:'البريد الإلكتروني',social:'تابع سونوز ماكينة',skip:'انتقل إلى المحتوى',faq:'ما الذي ينبغي مراعاته؟',check:'حدد المنتج والإنتاج المستهدف، وراجع تدفق الإنتاج كاملاً، وتحقق من المتطلبات الفنية باستخدام ورقة مواصفات حديثة وتجربة على عينة.',ask:'تحدث مع فريقنا عن منتجك وخطة الإنتاج.',models:'استعرض الطرز',latest:'اسألنا عن الطرازات المتاحة ومعلومات التوفر الحالية.'}
};
const catEn={
'kuruyemis-kavurma-makineleri':['Nut Roasting Machines','Belt roasting and drying lines','Nut roasting machines and belt roasting ovens configured for your product, desired roast and plant conditions. Machinery is planned to order; configuration and technical details are confirmed before production.'],
'kilavuzlu-kavurma-makineleri':['Guided Roasting Ovens','Rotary roasting systems','Guided and batch roasting oven options can be assessed according to product, batch size and plant layout.'],
'kuruyemis-tuzlama-ekipmanlari':['Nut Seasoning Equipment','Coating and seasoning','Equipment for applying salt and seasoning after roasting.'],
'kahve-kavurma-makineleri':['Coffee Roasting Machines','Roasting for coffee beans','Roaster options for coffee production workflows.'],
'isitma-yakit-sistemleri':['Heating and Fuel Systems','Heating solutions for production lines','Auxiliary systems assessed according to the heating needs of roasting lines.'],
'kuruyemis-paketleme-makineleri':['Nut Packaging Machines','From processing to packaging','Packaging machinery solutions for the final stages of nut processing.'],
'elekler':['Screening Machines','Separation and grading','Screening solutions selected by product size, separation objective and production flow.'],
'leblebi-kizartma-makineleri':['Roasted Chickpea Machines','Equipment for leblebi production','Machinery options for roasted chickpea processing.'],
'cekmeli-kuruyemis-firinlari':['Drawer Nut Ovens','Tray oven solutions','Tray arrangement, product type and plant layout should guide oven selection. Confirm fruit and vegetable drying suitability with the manufacturer.'],
'leblebi-seker-makineleri':['Candied Chickpea Machines','Confectionery equipment','Machines used in candied chickpea production.'],
'sari-leblebi-imalat-makineleri':['Yellow Chickpea Production Machines','Production line equipment','Machinery options for yellow roasted chickpea processing.'],
'secme-bantlari':['Sorting Conveyor Belts','Visual quality control','Sorting conveyors assessed by product flow, operator needs and compatibility with the screening line.'],
'draje-kaplama-makineleri':['Coating Machines','Coating processes','Machinery options for coating nuts and confectionery products.'],
'fritoz-cips-uretim-makineleri':['Fryer and Chip Production Machines','Frying production lines','Equipment for frying chips and similar products.']};
const catAr={
'kuruyemis-kavurma-makineleri':['آلات تحميص المكسرات','خطوط التحميص والتجفيف','آلات تحميص وأفران بالسير تُهيأ وفق المنتج ونتيجة التحميص وظروف المصنع. يُخطط للتكوين حسب الطلب وتُؤكد التفاصيل الفنية قبل الإنتاج.'],
'kilavuzlu-kavurma-makineleri':['أفران التحميص الموجهة','أنظمة التحميص الدوارة','يمكن تقييم خيارات أفران التحميص الموجهة والدفعات بحسب المنتج وحجم الدفعة وتخطيط المصنع.'],
'kuruyemis-tuzlama-ekipmanlari':['معدات تتبيل المكسرات','التغطية والتتبيل','معدات لإضافة الملح والتوابل بعد التحميص.'],
'kahve-kavurma-makineleri':['آلات تحميص القهوة','تحميص حبوب القهوة','خيارات للتحميص بما يلائم سير إنتاج القهوة.'],
'isitma-yakit-sistemleri':['أنظمة التدفئة والوقود','حلول تدفئة لخطوط الإنتاج','أنظمة مساعدة تُختار وفق احتياجات التدفئة في خطوط التحميص.'],
'kuruyemis-paketleme-makineleri':['آلات تعبئة المكسرات','من المعالجة إلى التعبئة','حلول آلات التعبئة للمراحل النهائية من معالجة المكسرات.'],
'elekler':['آلات الغربلة','الفصل والتصنيف','حلول غربلة تُختار بحسب حجم المنتج وهدف الفصل وطاقة الخط.'],
'leblebi-kizartma-makineleri':['آلات الحمص المحمص','معدات إنتاج اللبليبي','خيارات آلات لمعالجة الحمص المحمص.'],
'cekmeli-kuruyemis-firinlari':['أفران المكسرات ذات الأدراج','حلول أفران الصواني','يُراعى ترتيب الصواني ونوع المنتج وطاقة المصنع عند اختيار الفرن. يرجى تأكيد ملاءمته لتجفيف الفاكهة والخضروات مع الشركة المصنعة.'],
'leblebi-seker-makineleri':['آلات الحمص المحلى','معدات الحلويات','آلات تُستخدم في مراحل إنتاج الحمص المحلى.'],
'sari-leblebi-imalat-makineleri':['آلات إنتاج الحمص الأصفر','معدات خط الإنتاج','خيارات آلات معالجة الحمص المحمص الأصفر.'],
'secme-bantlari':['سيور فرز المنتجات','مراقبة الجودة البصرية','سيور فرز تُقيّم بحسب تدفق المنتج واحتياجات المشغل والتوافق مع خط الغربلة.'],
'draje-kaplama-makineleri':['آلات تغليف الدراجيه','عمليات التغطية','خيارات آلات لتغطية المكسرات ومنتجات الحلويات.'],
'fritoz-cips-uretim-makineleri':['آلات القلي وإنتاج الرقائق','خطوط إنتاج القلي','معدات لقلي رقائق البطاطس والمنتجات المشابهة.']};
const articleEn={
'kuruyemis-kavurma-makinesi-secimi':['How to Choose a Nut Roasting Machine','Compare product characteristics, verified output, line layout, energy supply, cleaning and service requirements.'],
'kavurma-ve-kurutma-arasindaki-fark':['Roasting vs Drying: Two Different Production Goals','Understand moisture control and flavour development as separate process goals.'],
'findik-kavurma-makinesi-secimi':['Hazelnut Roasting Machine: How to Specify One','A practical guide to samples, roast profile, shell handling and made-to-order fit.'],
'kuruyemis-uretim-hatti-planlama':['How to Plan a Nut Processing Line','A practical starting point for equipment sequence, space and production flow.'],
'kuruyemis-kavurma-makinesi-fiyati':['Nut Roasting Machine Prices: Comparing Quotes','Clarify manufacturing scope, energy, automation and commissioning before comparing offers.'],
'istege-gore-kuruyemis-kavurma-makinesi':['Custom Nut Roasting Machine: Made to Order','Learn how to specify a nut roaster around your product, roast profile, site and process requirements.'],
'kuruyemis-uretim-hatti-kurulum-maliyeti':['Nut Processing Line Setup Costs','Account for feeding, cooling, packaging, utilities, layout and commissioning.'],
'leblebi-uretim-hatti-makineleri':['Roasted Chickpea Production Line: Equipment and Process','Review chickpea preparation, heating, roasting, screening and packaging as a complete line.'],
'elektrikli-dogalgazli-kavurma-makinesi-secimi':['Electric or Gas Roasting: Choosing a Heat Source','Compare site infrastructure, process control, operating conditions and service requirements.'],
'kuruyemis-paketleme-makinesi-gramaj-secimi':['Choosing a Nut Packaging Machine and Pack Weight','Match pack format, target weight, product flow and required output.'],
'draje-kaplama-makinesi-secimi':['How to Choose a Coating Machine','Assess batch size, product movement, coating process and cleaning needs.'],
'kahve-kavurma-makinesi-secimi':['How to Choose a Coffee Roaster','Define the bean, batch profile, repeatability, cooling and production requirements.'],
'bantli-donerli-kavurma-makinesi-secimi':['Belt-Type or Rotary Nut Roaster?','Compare the two machine types through product trials, site layout, technical drawings and quotation scope.'],
'denizli-kuruyemis-makinesi-imalati':['Nut Processing Machinery Made in Denizli: Quotation Guide','A guide to defining requirements, technical discussions, samples and made-to-order quotations from a nut roasting machine manufacturer in Denizli.'],
'kuruyemis-kavurma-makinesi-teklif-talebi':['Nut Roasting Machine Quote: What to Send the Manufacturer','A practical request checklist for product, target result, site conditions, machine type and quotation scope.'],
'kuruyemis-kavurma-makinesi-teknik-cizim-kontrolu':['Nut Roaster Technical Drawing: Pre-Order Checklist','Check dimensions, transport access, line connections, utilities and maintenance clearances before approving a made-to-order drawing.']};
const articleAr={
'kuruyemis-kavurma-makinesi-secimi':['كيفية اختيار آلة تحميص المكسرات','قارن خصائص المنتج والإنتاج الفعلي وتخطيط الخط والطاقة والتنظيف ومتطلبات الصيانة.'],
'kavurma-ve-kurutma-arasindaki-fark':['التحميص والتجفيف: هدفان مختلفان للإنتاج','افهم التحكم في الرطوبة وتطوير النكهة بوصفهما هدفين منفصلين للعملية.'],
'findik-kavurma-makinesi-secimi':['اختيار محمصة البندق: تحديد المواصفات','دليل للعينات وملف التحميص والقشرة والملاءمة للتصنيع حسب الطلب.'],
'kuruyemis-uretim-hatti-planlama':['كيفية تخطيط خط معالجة المكسرات','بداية عملية لتسلسل المعدات والمساحة وتدفق الإنتاج.'],
'kuruyemis-kavurma-makinesi-fiyati':['أسعار آلات تحميص المكسرات: مقارنة عروض الأسعار','حدد نطاق العمل والطاقة والطاقة التشغيلية والأتمتة والتشغيل قبل مقارنة العروض.'],
'istege-gore-kuruyemis-kavurma-makinesi':['محمصة مكسرات حسب الطلب','دليل لتحديد محمصة المكسرات وفق المنتج ونتيجة التحميص وظروف الموقع ومتطلبات العملية.'],
'kuruyemis-uretim-hatti-kurulum-maliyeti':['تكلفة إنشاء خط معالجة المكسرات','احسب التغذية والتبريد والتعبئة والمرافق والتخطيط والتشغيل الأولي.'],
'leblebi-uretim-hatti-makineleri':['خط إنتاج الحمص المحمص: المعدات وتسلسل العمليات','راجع إعداد الحمص والتسخين والتحميص والغربلة والتعبئة كخط متكامل.'],
'elektrikli-dogalgazli-kavurma-makinesi-secimi':['التحميص الكهربائي أم بالغاز: اختيار مصدر الحرارة','قارن بنية الموقع والتحكم بالعملية وظروف التشغيل ومتطلبات الخدمة.'],
'kuruyemis-paketleme-makinesi-gramaj-secimi':['اختيار آلة تعبئة المكسرات ووزن العبوة','وازن بين شكل العبوة والوزن المستهدف وتدفق المنتج والإنتاج المطلوب.'],
'draje-kaplama-makinesi-secimi':['كيفية اختيار آلة التغطية','قيّم حجم الدفعة وحركة المنتج وعملية التغطية ومتطلبات التنظيف.'],
'kahve-kavurma-makinesi-secimi':['كيفية اختيار محمصة القهوة','حدد نوع الحبوب وملف الدفعة وقابلية التكرار والتبريد ومتطلبات الإنتاج.'],
'bantli-donerli-kavurma-makinesi-secimi':['محمصة المكسرات بالسير أم الدوارة؟','قارن بين النوعين من خلال تجربة المنتج وتخطيط الموقع والرسم الفني ونطاق العرض.'],
'denizli-kuruyemis-makinesi-imalati':['تصنيع آلات المكسرات في دنيزلي: دليل طلب العرض','دليل لتحديد الاحتياجات والنقاش الفني والعينات والعروض المصنّعة حسب الطلب من مصنع آلات تحميص المكسرات في دنيزلي.'],
'kuruyemis-kavurma-makinesi-teklif-talebi':['عرض سعر آلة تحميص المكسرات: ما الذي ترسله للمصنّع؟','قائمة عملية لطلب العرض تشمل المنتج والنتيجة المستهدفة وظروف الموقع ونوع الآلة ونطاق العرض.'],
'kuruyemis-kavurma-makinesi-teknik-cizim-kontrolu':['الرسم الفني لمحمصة المكسرات: قائمة تحقق قبل الطلب','تحقق من الأبعاد ومسار النقل ووصلات الخط والمرافق ومساحات الصيانة قبل اعتماد الرسم المصنّع حسب الطلب.']};
const productTerms={
'Kuruyemiş Kavurma Makinesi':'Nut Roasting Machine','Kavurma ve Kurutma Makinesi':'Roasting and Drying Machine','Leblebi Kavurma Makinesi':'Roasted Chickpea Machine','Kahve Kavurma Makinesi':'Coffee Roaster','Kılavuzlu Kavurma Fırını':'Guided Roasting Oven','Tuzlama Makinesi':'Seasoning Machine','Prina Yakıt Makinesi':'Olive Pomace Fuel System','Yarı Otomatik Dolum Sistemi':'Semi-Automatic Filling System','Yarı Otomatik Dolum Makinesi':'Semi-Automatic Filling Machine','Otomatik Kuruyemiş Paketleme Makinesi':'Automatic Nut Packaging Machine','Otomatik Paketleme Makinesi':'Automatic Packaging Machine','Kuruyemiş Eleği':'Nut Screening Machine','Çekmeceli Kuruyemiş Fırını':'Drawer Nut Oven','Nohut Sulama Makinesi':'Chickpea Watering Machine','Bandırma Nohut Makinesi':'Chickpea Dipping Machine','Draje Bakır Çift Kazan':'Copper Double Coating Pan','Draje Krom Çift Kazan':'Stainless Steel Double Coating Pan','Draje Krom Tek Kazan':'Stainless Steel Single Coating Pan','Sarı Nohut Yapma Makinesi':'Yellow Chickpea Processing Machine','Nohut Isıtma Makinesi':'Chickpea Heating Machine','Kuruyemiş Seçme Bandı':'Nut Sorting Conveyor','Draje Kaplama Makinesi':'Coating Machine','Fritöz ve Cips Üretim Makinesi':'Fryer and Chip Production Machine'};
const productAr={'Kuruyemiş Kavurma Makinesi':'آلة تحميص المكسرات','Kavurma ve Kurutma Makinesi':'آلة التحميص والتجفيف','Leblebi Kavurma Makinesi':'آلة تحميص الحمص','Kahve Kavurma Makinesi':'محمصة القهوة','Kılavuzlu Kavurma Fırını':'فرن التحميص الموجه','Tuzlama Makinesi':'آلة التمليح','Prina Yakıt Makinesi':'نظام وقود تفل الزيتون','Yarı Otomatik Dolum Sistemi':'نظام وزن وتعبئة شبه آلي','Yarı Otomatik Dolum Makinesi':'آلة تعبئة شبه آلية','Otomatik Kuruyemiş Paketleme Makinesi':'آلة تعبئة المكسرات آلياً','Otomatik Paketleme Makinesi':'آلة تعبئة آلية','Kuruyemiş Eleği':'آلة غربلة المكسرات','Çekmeceli Kuruyemiş Fırını':'فرن مكسرات بالأدراج','Nohut Sulama Makinesi':'آلة ترطيب الحمص','Bandırma Nohut Makinesi':'آلة غمس الحمص','Draje Bakır Çift Kazan':'حوض تغطية نحاسي مزدوج','Draje Krom Çift Kazan':'حوض تغطية مزدوج من الفولاذ المقاوم للصدأ','Draje Krom Tek Kazan':'حوض تغطية مفرد من الفولاذ المقاوم للصدأ','Sarı Nohut Yapma Makinesi':'آلة معالجة الحمص الأصفر','Nohut Isıtma Makinesi':'آلة تسخين الحمص','Kuruyemiş Seçme Bandı':'سير فرز المكسرات','Draje Kaplama Makinesi':'آلة تغطية الدراجيه','Fritöz ve Cips Üretim Makinesi':'آلة قلي وإنتاج الرقائق'};

const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const whatsappSvg='<svg viewBox="0 0 32 32" aria-hidden="true" focusable="false"><path d="M16.02 3.2A12.7 12.7 0 0 0 5.1 22.38l-1.7 6.2 6.35-1.67A12.72 12.72 0 1 0 16.02 3.2Zm0 23.16c-1.96 0-3.88-.52-5.55-1.51l-.4-.24-3.77.99 1.01-3.67-.26-.42a10.45 10.45 0 1 1 8.97 4.85Zm5.74-7.83c-.31-.16-1.84-.91-2.13-1.01-.28-.11-.49-.16-.7.16-.2.31-.8 1.01-.98 1.22-.18.2-.36.23-.67.08-.31-.16-1.31-.49-2.49-1.54-.92-.82-1.54-1.84-1.72-2.15-.18-.31-.02-.48.14-.64.14-.14.31-.36.46-.54.15-.18.2-.31.31-.52.1-.21.05-.39-.03-.55-.08-.15-.7-1.69-.96-2.31-.25-.6-.51-.52-.7-.53h-.6c-.21 0-.55.08-.83.39-.28.31-1.08 1.06-1.08 2.59s1.1 3 1.25 3.21c.16.2 2.17 3.31 5.26 4.65.74.32 1.31.51 1.76.65.74.24 1.42.2 1.95.12.59-.09 1.84-.75 2.1-1.48.26-.72.26-1.35.18-1.48-.08-.13-.28-.2-.59-.36Z"/></svg>';
const titleFor=(route,locale,categories,products,articles)=>{
 const dict=locale==='en'?articleEn:articleAr;
 const a=articles.find(x=>route===`bilgi-merkezi/${x.slug}`);if(a)return dict[a.slug]?.[0]||a.title;
 const p=products.find(x=>route===`urunler/${x.slug}`);if(p){let name=p.name;const terms=locale==='en'?productTerms:productAr;for(const [tr,to] of Object.entries(terms))name=name.replace(tr,to);return name;}
 const c=categories.find(x=>route===`urunler/${x.slug}`);if(c)return (locale==='en'?catEn:catAr)[c.slug]?.[0]||c.name;
 const base={'':locale==='en'?'Nut Roasting Machine Manufacturer in Denizli':'مصنع آلات تحميص المكسرات في دنيزلي','urunler':locale==='en'?'Nut and Food Processing Machines':'آلات معالجة المكسرات والأغذية','bilgi-merkezi':locale==='en'?'Food Processing Guides':'أدلة معالجة الأغذية','hakkimizda':locale==='en'?'About Sonsuz Makina':'من نحن','iletisim':locale==='en'?'Contact and Request a Quote':'اتصل بنا واطلب عرض سعر','galeri':locale==='en'?'Machine and Production Gallery':'معرض الآلات والإنتاج','referanslar':locale==='en'?'Our References':'أعمالنا','e-katalog':locale==='en'?'Machine E-Catalog':'كتالوج الآلات'};
 return base[route]||base[''];
};

export function buildLocales({root,routes,categories,products,articles}){
 for(const locale of ['en','ar']){
  const t=labels[locale];
  const brandStamp=locale==='en'?'SONSUZ MAKINA / DENIZLI':'سونوز ماكينة / دنيزلي';
  const cityStamp=locale==='en'?'Denizli, Türkiye':'دنيزلي، تركيا';
  const pathFor=r=>`/${locale}${r==='/'?'/' : r}`;
  const catalogTable=(slug)=>{const rows=catalogTables[slug];if(!rows?.length)return '';const labels=locale==='en'?['Model','Overall dimensions (mm)','Heating / operation','Minimum','Maximum','Average']:['الطراز','الأبعاد الإجمالية (مم)','التسخين / التشغيل','الحد الأدنى','الحد الأقصى','المتوسط'];const note=locale==='en'?'Source: Sonsuz Makina e-catalogue. As configurations are made to order, confirm dimensions and technical details against the current drawing. Confirm the measurement conditions for minimum, maximum and average values with the team.':'المصدر: كتالوج سونوز ماكينة. تُنتج الآلات وفق الطلب؛ لذا يجب تأكيد الأبعاد والتفاصيل الفنية وفق الرسم الفني الأحدث. يرجى تأكيد شروط قياس القيم الدنيا والعليا والمتوسطة مع الفريق.';return `<section class="catalog-tech"><div class="wrap"><div class="section-heading"><div><span class="eyebrow">${locale==='en'?'TECHNICAL DATA FROM THE E-CATALOGUE':'بيانات فنية من الكتالوج'}</span><h2>${locale==='en'?'Models and catalogue values':'الطرازات وقيم الكتالوج'}</h2></div></div><p class="catalog-source-note">${note}</p><div class="guide-table-wrap"><table class="catalog-tech-table"><thead><tr>${labels.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(x=>`<tr><th scope="row">${esc(x.model)}</th><td>${esc(x.dimensions)}</td><td>${esc(x.heating||x.operation||'—')}</td><td>${esc(x.min)}</td><td>${esc(x.max)}</td><td>${esc(x.average)}</td></tr>`).join('')}</tbody></table></div><p class="catalog-source-note">${note}</p></div></section>`;};
  const productTech=(slug)=>{const x=productCatalogSpecs[slug]?.[0];if(!x)return '';const l=locale==='en'?['E-CATALOGUE TECHNICAL DATA','Catalogue details','Overall dimensions (mm)','Heating','Minimum catalogue value','Maximum catalogue value','Average catalogue value']:['بيانات فنية من الكتالوج','تفاصيل الطراز','الأبعاد الإجمالية (مم)','التسخين','القيمة الدنيا في الكتالوج','القيمة العليا في الكتالوج','متوسط القيمة في الكتالوج'];const note=locale==='en'?'Source: Sonsuz Makina e-catalogue. Confirm the made-to-order configuration, dimensions and measurement conditions against the current technical drawing.':'المصدر: كتالوج سونوز ماكينة. يرجى تأكيد التكوين المصنّع حسب الطلب والأبعاد وشروط القياس وفق الرسم الفني الأحدث.';return `<section class="spec-section"><div class="wrap spec-grid"><div><span class="eyebrow">${l[0]}</span><h2>${esc(x.model)}<br><em>${l[1]}</em></h2></div><div><dl class="spec-list"><div><dt>${l[2]}</dt><dd>${esc(x.dimensions)}</dd></div><div><dt>${l[3]}</dt><dd>${esc(x.heating)}</dd></div><div><dt>${l[4]}</dt><dd>${esc(x.min)}</dd></div><div><dt>${l[5]}</dt><dd>${esc(x.max)}</dd></div><div><dt>${l[6]}</dt><dd>${esc(x.average)}</dd></div></dl><p class="fineprint">${note}</p></div></div></section>`;};
  const href=(r,label)=>`<a href="${pathFor(r)}">${label}</a>`;
  const navFor=(route)=>`<header class="site-header"><div class="wrap nav"><a class="brand" href="${pathFor('/')}" aria-label="Sonsuz Makina"><img class="brand-logo" src="/assets/sonsuz-logo.svg" alt="Sonsuz Makina" width="195" height="55"></a><nav class="desktop-nav" aria-label="${t.machines}">${href('/urunler/',t.machines)}${href('/hakkimizda/',t.about)}${href('/galeri/',t.gallery)}${href('/e-katalog/',t.catalog)}${href('/bilgi-merkezi/',t.guides)}${href('/iletisim/',t.contact)}</nav><a class="nav-cta" href="${pathFor('/iletisim/')}">${t.talk} ↗</a><details class="mobile-nav-menu"><summary aria-label="${t.machines}">☰</summary><nav>${href('/urunler/',t.machines)}${href('/hakkimizda/',t.about)}${href('/galeri/',t.gallery)}${href('/e-katalog/',t.catalog)}${href('/bilgi-merkezi/',t.guides)}${href('/iletisim/',t.contact)}</nav></details><nav class="language-switcher" aria-label="Language"><a class="language-option${locale==='tr'?' is-current':''}" href="${route}" lang="tr" hreflang="tr" aria-label="Türkçe" title="Türkçe"><span class="language-flag" aria-hidden="true">🇹🇷</span><span>TR</span></a><a class="language-option${locale==='en'?' is-current':''}" href="/en${route==='/'?'/':route}" lang="en" hreflang="en" aria-label="English" title="English"><span class="language-flag" aria-hidden="true">🇬🇧</span><span>EN</span></a><a class="language-option${locale==='ar'?' is-current':''}" href="/ar${route==='/'?'/':route}" lang="ar" hreflang="ar" aria-label="العربية" title="العربية"><span class="language-flag" aria-hidden="true">🇸🇦</span><span>AR</span></a></nav></div></header>`;
  const footer=`<footer class="footer"><div class="wrap footer-lead"><span class="footer-lead-label">${brandStamp}</span><div><h2>${t.footer}</h2><a href="${pathFor('/iletisim/')}">${t.talk} ↗</a></div></div><div class="wrap footer-grid"><div><a class="brand footer-brand" href="${pathFor('/')}"><img class="brand-logo" src="/assets/sonsuz-logo.svg" alt="Sonsuz Makina" width="195" height="55"></a><p>${t.desc}</p></div><div><b>${t.machines}</b>${href('/urunler/',t.all)}${href('/galeri/',t.gallery)}${href('/referanslar/',locale==='en'?'References':'عملاؤنا')}${href('/e-katalog/',t.catalog)}${href('/bilgi-merkezi/',t.guides)}${href('/hakkimizda/',t.about)}</div><div><b>${t.contact}</b><a href="tel:+902582659990">+90 258 265 99 90</a><a href="mailto:info@sonsuzmakina.com">info@sonsuzmakina.com</a><span>${t.address}</span></div></div><nav class="footer-socials" aria-label="${t.social}"><a href="https://www.instagram.com/makinasonsuz/" target="_blank" rel="noopener noreferrer" aria-label="Instagram" title="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle class="social-dot" cx="18" cy="6" r="1"/></svg></a><a href="https://www.youtube.com/@sonsuzmakina" target="_blank" rel="noopener noreferrer" aria-label="YouTube" title="YouTube"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M23 7.1a3 3 0 0 0-2.1-2.2C19 4.4 12 4.4 12 4.4s-7 0-8.9.5A3 3 0 0 0 1 7.1 31 31 0 0 0 .5 12a31 31 0 0 0 .5 4.9 3 3 0 0 0 2.1 2.2c1.9.5 8.9.5 8.9.5s7 0 8.9-.5a3 3 0 0 0 2.1-2.2 31 31 0 0 0 .5-4.9ZM9.7 15.5v-7l6 3.5-6 3.5Z"/></svg></a><a href="https://www.linkedin.com/in/sonsuzmakina/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" title="LinkedIn"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5.2 3.3a2.2 2.2 0 1 1 0 4.4 2.2 2.2 0 0 1 0-4.4ZM3.3 9h3.8v12H3.3zm6.2 0h3.6v1.6h.1A4 4 0 0 1 16.8 8c4 0 4.7 2.6 4.7 6v7h-3.8v-6.2c0-1.5 0-3.4-2.1-3.4s-2.5 1.6-2.5 3.3V21H9.5z"/></svg></a></nav><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Sonsuz Makina</span><span>${cityStamp}</span></div></footer>`;
  const renderBody=(r)=>{
   const p=products.find(x=>r===`urunler/${x.slug}`), c=categories.find(x=>r===`urunler/${x.slug}`), a=articles.find(x=>r===`bilgi-merkezi/${x.slug}`),tTitle=titleFor(r,locale,categories,products,articles);
   const productName=x=>{let n=x.name;for(const [tr,to] of Object.entries(locale==='en'?productTerms:productAr))n=n.replace(tr,to);return n;};
   const modelTerms={en:{'Bandırma Nohut':'Dipped Chickpea','Bakır Çift Kazan':'Copper Double Pan','Krom Çift Kazan':'Stainless Steel Double Pan','Krom Tek Kazan':'Stainless Steel Single Pan','Sarı Nohut':'Yellow Chickpea','Nohut Isıtma':'Chickpea Heating','Seçme Bandı':'Sorting Conveyor','Draje Kaplama':'Coating','Fritöz ve Cips':'Fryer and Chips','14 Çekmeceli':'14-Drawer','7 Çekmeceli':'7-Drawer','Leblebi Kavurma':'Roasted Chickpea Roaster','Prina Yakıt':'Olive Pomace Fuel','2 Kefeli':'2-Head','4 Kefeli':'4-Head','5 Kefeli':'5-Head','Elek':'Screening Machine','Nohut Sulama':'Chickpea Moistening','HT Manuel':'HT Manual'},ar:{'Bandırma Nohut':'حمص مغمور','Bakır Çift Kazan':'حوض نحاسي مزدوج','Krom Çift Kazan':'حوض مزدوج من الفولاذ المقاوم للصدأ','Krom Tek Kazan':'حوض مفرد من الفولاذ المقاوم للصدأ','Sarı Nohut':'حمص أصفر','Nohut Isıtma':'تسخين الحمص','Seçme Bandı':'سير فرز','Draje Kaplama':'تغطية','Fritöz ve Cips':'قلي ورقائق','14 Çekmeceli':'14 درجاً','7 Çekmeceli':'7 أدراج','Leblebi Kavurma':'تحميص الحمص المحمص','Prina Yakıt':'وقود تفل الزيتون','2 Kefeli':'رأسان للوزن','4 Kefeli':'4 رؤوس للوزن','5 Kefeli':'5 رؤوس للوزن','Elek':'آلة غربلة','Nohut Sulama':'ترطيب الحمص','HT Manuel':'HT يدوي'}};
   const modelName=x=>{let n=x.model;for(const [tr,to] of Object.entries(modelTerms[locale]))n=n.replace(tr,to);return n;};
   const productCard=x=>`<article class="product-card"><a class="product-card-link" href="${pathFor(`/urunler/${x.slug}/`)}"><div class="product-art"><img src="/assets/products/${esc(x.image)}" alt="${esc(productName(x))}" loading="lazy" width="700" height="560"></div><div class="product-info"><span class="eyebrow">${t.model} ${esc(modelName(x))}</span><h3>${esc(productName(x))}</h3><p>${locale==='en'?`A Sonsuz Makina model for ${esc((catEn[x.category]||[])[0]||'food processing')}. Confirm current specifications and suitability with our team.`:`طراز من سونوز ماكينة لـ ${esc((catAr[x.category]||[])[0]||'معالجة الأغذية')}. يرجى تأكيد المواصفات والملاءمة الحالية مع فريقنا.`}</p><span class="card-link">${t.details} ↗</span></div></a></article>`;
   if(r==='')return `<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><span class="eyebrow light">${brandStamp}</span><h1>${locale==='en'?'Industrial food processing machinery.':'آلات صناعية لتجهيز الأغذية.'}<br><em>${locale==='en'?'Built around your production.':'مصممة وفق احتياجات إنتاجك.'}</em></h1><p>${t.intro}</p><div class="hero-actions"><a class="button button-light" href="${pathFor('/urunler/')}">${t.discover} ↗</a><a class="text-link" href="${pathFor('/iletisim/')}">${t.talk} →</a></div><div class="hero-path"><a href="${pathFor('/urunler/kuruyemis-kavurma-makineleri/')}"><small>01 / ${locale==='en'?'THERMAL PROCESSING':'المعالجة الحرارية'}</small><b>${locale==='en'?'Roasting & drying':'التحميص والتجفيف'} ↗</b></a><a href="${pathFor('/urunler/elekler/')}"><small>02 / ${locale==='en'?'PROCESSING':'المعالجة'}</small><b>${locale==='en'?'Coating & screening':'التغطية والغربلة'} ↗</b></a><a href="${pathFor('/urunler/kuruyemis-paketleme-makineleri/')}"><small>03 / ${locale==='en'?'FINISHING':'المرحلة النهائية'}</small><b>${locale==='en'?'Filling & packing':'الوزن والتعبئة'} ↗</b></a></div></div><div class="hero-visual"><video class="locale-video" controls preload="none" poster="/assets/hero/uretim-video.jpg" playsinline><source src="/assets/hero/sonsuz-makina-uretim-v2.mp4" type="video/mp4"></video></div></div></section><section class="section wrap"><div class="section-heading"><div><span class="eyebrow">${t.group}</span><h2>${locale==='en'?'Explore our machine range':'اكتشف مجموعة آلاتنا'}</h2></div></div><div class="category-grid">${categories.map(x=>{const z=(locale==='en'?catEn:catAr)[x.slug];return `<a class="category-card" href="${pathFor(`/urunler/${x.slug}/`)}"><span class="category-photo"><img src="/assets/categories/${x.slug}.webp" alt="${esc(z?.[0]||x.name)}" loading="lazy" width="700" height="700"></span><span class="category-meta"><h3>${esc(z?.[0]||x.name)}</h3><p>${esc(z?.[1]||'')}</p><span class="card-link">${t.details} ↗</span></span></a>`}).join('')}</div></section>`;
   if(r==='urunler')return `<section class="page-intro wrap"><span class="eyebrow">${t.machines} / ${products.length}</span><h1>${locale==='en'?'Find the right machine for your line.':'اختر الآلة المناسبة لخط إنتاجك.'}</h1><p>${t.desc}</p></section><section class="wrap section compact"><div class="product-grid">${products.map(productCard).join('')}</div></section>`;
   if(c){const cz=(locale==='en'?catEn:catAr)[c.slug]||[c.name,'',t.desc];const ps=products.filter(x=>x.category===c.slug);return `<section class="page-intro wrap"><div class="breadcrumb"><a href="${pathFor('/')}">${t.home}</a><span>/</span><a href="${pathFor('/urunler/')}">${t.machines}</a></div><span class="eyebrow">${t.group}</span><h1>${esc(cz[0])}</h1><p>${esc(cz[2])}</p></section><section class="wrap section compact"><div class="product-grid">${ps.map(productCard).join('')}</div><div class="references-cta"><p>${t.latest}</p><a class="button button-dark" href="${pathFor('/iletisim/')}">${t.contact} ↗</a></div></section>${catalogTable(c.slug)}`;}
   if(p)return `<section class="page-intro wrap"><div class="breadcrumb"><a href="${pathFor('/')}">${t.home}</a><span>/</span><a href="${pathFor('/urunler/')}">${t.machines}</a></div><span class="eyebrow">${t.model} ${esc(modelName(p))}</span><h1>${esc(productName(p))}</h1><p>${locale==='en'?`A production solution in the ${((catEn[p.category]||[])[0]||'food machinery')} range. Final configuration depends on product, process and plant requirements.`:`حل إنتاج ضمن فئة ${((catAr[p.category]||[])[0]||'آلات الأغذية')}. يعتمد التكوين النهائي على المنتج والعملية ومتطلبات المصنع.`}</p></section><section class="wrap product-detail-grid section compact"><div class="detail-art"><img src="/assets/products/${esc(p.image)}" alt="${esc(productName(p))}" width="700" height="560" fetchpriority="high"></div><div class="contact-panel"><span class="eyebrow">${t.model} ${esc(modelName(p))}</span><h2>${locale==='en'?'Discuss your product and line':'ناقش منتجك وخط الإنتاج'}</h2><p>${t.check}</p><a class="button button-dark" href="${pathFor('/iletisim/')}">${t.request} ↗</a><p>${t.latest}</p></div></section>${productTech(p.slug)}`;
   if(r==='bilgi-merkezi')return `<section class="page-intro wrap"><span class="eyebrow">${t.guides}</span><h1>${locale==='en'?'Production knowledge for better decisions':'معلومات الإنتاج لاتخاذ قرارات أفضل'}</h1><p>${t.desc}</p></section><section class="wrap section compact"><div class="article-grid">${articles.map(x=>{const guide=localizedGuides[locale][x.slug],z=guide?[guide.title,guide.desc]:(locale==='en'?articleEn:articleAr)[x.slug]||[x.title,t.process];return `<a class="article-card" href="${pathFor(`/bilgi-merkezi/${x.slug}/`)}"><span class="eyebrow">${t.guides}</span><h2>${esc(z[0])}</h2><p>${esc(z[1])}</p><span class="card-link">${t.details} ↗</span></a>`}).join('')}</div></section>`;
   if(a){const guide=localizedGuides[locale][a.slug],az=guide?[guide.title,guide.desc]:(locale==='en'?articleEn:articleAr)[a.slug]||[a.title,t.process];return `<article class="wrap prose-page"><div class="breadcrumb"><a href="${pathFor('/')}">${t.home}</a><span>/</span><a href="${pathFor('/bilgi-merkezi/')}">${t.guides}</a></div><span class="eyebrow">${t.guides}</span><h1>${esc(az[0])}</h1><p class="lead">${esc(az[1])}</p><div class="prose">${(guide?.sections||[[t.faq,t.check],[locale==='en'?'Assess the complete production flow':'قيّم تدفق الإنتاج كاملاً',t.process],[locale==='en'?'Verify technical details':'تحقق من التفاصيل الفنية',t.latest]]).map(([heading,body])=>`<section><h2>${esc(heading)}</h2><p>${esc(body)}</p></section>`).join('')}<aside><b>${t.ask}</b><p>${t.latest}</p><a href="${pathFor('/iletisim/')}">${t.contact} →</a></aside></div></article>`;}
   const core={
    hakkimizda:[t.about,locale==='en'?'Engineering production solutions in Denizli.':'حلول هندسية للإنتاج من دنيزلي.',t.desc],
    iletisim:[t.contact,t.ask,t.address],
    galeri:[t.gallery,locale==='en'?'A closer look at our machines and production.':'لقطات عن قرب لآلاتنا وإنتاجنا.',t.desc],
    referanslar:[locale==='en'?'References':'أعمالنا',t.desc,t.ask],
    'e-katalog':[t.catalog,locale==='en'?'Explore the machine range in our catalogue.':'استكشف مجموعة الآلات في الكتالوج.',t.latest]
   }[r]||[tTitle,t.desc,t.ask];
   if(r==='iletisim')return `<section class="page-intro wrap"><span class="eyebrow">${core[0]}</span><h1>${core[1]}</h1><p>${t.desc}</p></section><section class="wrap contact-grid section compact"><div class="contact-panel"><h2>${t.talk}</h2><p><b>${t.phone}:</b> <a href="tel:+902582659990">+90 258 265 99 90</a></p><p><b>${t.email}:</b> <a href="mailto:info@sonsuzmakina.com">info@sonsuzmakina.com</a></p><p><b>${t.address}</b></p><a class="button button-dark" href="https://wa.me/905378896885">WhatsApp ↗</a></div></section>`;
   return `<section class="page-intro wrap"><div class="breadcrumb"><a href="${pathFor('/')}">${t.home}</a></div><span class="eyebrow">${brandStamp}</span><h1>${esc(core[0])}</h1><p>${esc(core[1])}</p></section><section class="wrap section compact"><p>${esc(core[2])}</p><a class="button button-dark" href="${pathFor('/iletisim/')}">${t.contact} ↗</a>${r==='e-katalog'?`<p><a href="/assets/catalog/sonsuz-makina-katalog-v2.pdf" target="_blank" rel="noopener">${t.catalog} ↗</a></p>`:''}${r==='galeri'?`<div class="gallery-grid">${fs.readdirSync('public/assets/gallery').filter(f=>f.endsWith('.webp')).sort().map((f,i)=>`<figure><img src="/assets/gallery/${f}" alt="Sonsuz Makina production photo ${i+1}" loading="lazy" width="1200" height="900"></figure>`).join('')}</div>`:''}</section>`;
  };
  for(const route of routes){
   const r=route.replace(/^\//,'').replace(/\/$/,'');
   const canonical=site+pathFor(route);
   const title=titleFor(r,locale,categories,products,articles);
   const article=articles.find(x=>r===`bilgi-merkezi/${x.slug}`);
   const metaTitle=article?(localizedGuides[locale][article.slug]?.seoTitle||title):title;
   const product=products.find(x=>r===`urunler/${x.slug}`);
   const category=categories.find(x=>r===`urunler/${x.slug}`);
   const desc=article?(localizedGuides[locale][article.slug]?.desc||(locale==='en'?articleEn[article.slug]?.[1]:articleAr[article.slug]?.[1])):product?(locale==='en'?`${title}: a Sonsuz Makina model for food processing. Confirm the current technical sheet and configuration for your product and plant.`:`${title}: طراز من سونوز ماكينة لمعالجة الأغذية. يرجى تأكيد ورقة المواصفات والتكوين المناسب لمنتجك ومصنعك.`):category?((locale==='en'?catEn:catAr)[category.slug]?.[2]||labels[locale].desc):r==='iletisim'?t.ask:r==='galeri'?(locale==='en'?'View machine and production images from Sonsuz Makina.':'شاهد صور الآلات والإنتاج من سونوز ماكينة.'):r==='e-katalog'?t.latest:r==='hakkimizda'?t.desc:r==='urunler'?(locale==='en'?'Browse nut roasting, drying, screening, coating and packaging machines from Sonsuz Makina.':'استعرض آلات تحميص المكسرات وتجفيفها وغربلتها وتغطيتها وتعبئتها من سونوز ماكينة.'):r==='bilgi-merkezi'?(locale==='en'?'Practical guides to food processing machinery, production lines and equipment selection.':'أدلة عملية لآلات معالجة الأغذية وخطوط الإنتاج واختيار المعدات.'):labels[locale].desc;
   const hreflangPath=(lang)=>lang==='tr'?route:`/${lang}${route==='/'?'/':route}`;
   const image=product?`/assets/products/${product.image}`:category?`/assets/categories/${category.slug}.webp`:article?`/assets/products/${guideImage(article.slug)}`:r==='galeri'?'/assets/gallery/01.webp':'/assets/hero/uretim-video.jpg';
   const tech=product?productCatalogSpecs[product.slug]?.[0]:null;const schema=product?{'@context':'https://schema.org','@type':'Product',name:title,sku:product.model,image:`${site}${image}`,description:desc,brand:{'@type':'Brand',name:'Sonsuz Makina'},category:titleFor(`urunler/${product.category}`,locale,categories,products,articles),additionalProperty:tech?[['Overall dimensions (mm)',tech.dimensions],['Heating',tech.heating],['Minimum catalogue value',tech.min],['Maximum catalogue value',tech.max],['Average catalogue value',tech.average]].map(([name,value])=>({'@type':'PropertyValue',name,value})):undefined}:article?{'@context':'https://schema.org','@type':'Article',headline:title,description:desc,image:[`${site}${image}`],datePublished:article.date,dateModified:article.date,author:{'@type':'Organization',name:'Sonsuz Makina',url:`${site}${pathFor('/hakkimizda/')}`},publisher:{'@type':'Organization',name:'Sonsuz Makina',logo:{'@type':'ImageObject',url:`${site}/assets/sonsuz-logo.svg`}},mainEntityOfPage:canonical}:{'@context':'https://schema.org','@type':'WebPage',name:title,description:desc,url:canonical,inLanguage:locale==='en'?'en': 'ar'};
   const schemaScript=schema?`<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`:'';
   const cssFile=fs.readdirSync(path.join(root,'assets')).find(x=>/^app-.*\.css$/.test(x));
   const page=`<!doctype html><html lang="${locale}" dir="${t.dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#091f41"><title>${esc(metaTitle)} | Sonsuz Makina</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="tr" href="${site}${hreflangPath('tr')}"><link rel="alternate" hreflang="en" href="${site}${hreflangPath('en')}"><link rel="alternate" hreflang="ar" href="${site}${hreflangPath('ar')}"><link rel="alternate" hreflang="x-default" href="${site}${route}"><meta property="og:locale" content="${t.locale}"><meta property="og:title" content="${esc(metaTitle)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${site}${image}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${site}${image}"><link rel="icon" href="/favicon.png"><link rel="stylesheet" href="/assets/${cssFile}">${schemaScript}<style>html[dir=rtl] body{text-align:right;font-family:system-ui,'Noto Naskh Arabic',Tahoma,sans-serif}html[dir=rtl] .hero-path,html[dir=rtl] .hero-actions{direction:rtl}.language-picker{position:relative;margin-inline-start:12px;color:inherit}.language-picker summary{cursor:pointer;list-style:none;padding:10px;border:1px solid #ffffff40;border-radius:8px}.language-picker a{display:block;padding:9px 12px;background:#fff;color:#10223b;text-decoration:none}.mobile-nav-menu{display:none}.hero-visual{position:relative;min-height:0;height:auto;aspect-ratio:16/10;align-self:center;border-radius:clamp(80px,20vw,220px) clamp(80px,20vw,220px) 18px 18px}.locale-video{position:absolute;inset:0;display:block;width:100%;height:100%;min-height:0;object-fit:cover;object-position:center;background:#071b34;border-radius:inherit}.footer-socials a{font-weight:800;text-decoration:none;display:grid;place-items:center}@media(max-width:1000px){.mobile-nav-menu{display:block;position:relative}.mobile-nav-menu summary{cursor:pointer;font-size:24px;list-style:none}.mobile-nav-menu nav{position:absolute;right:0;top:100%;z-index:10;min-width:210px;padding:12px;background:#fff;box-shadow:0 10px 32px #071b3440}.mobile-nav-menu nav a{display:block;padding:10px}}@media(max-width:680px){.hero-visual{width:min(100%,550px)}.locale-video{min-height:0}}</style></head><body><a class="skip" href="#content">${t.skip}</a>${navFor(route)}<main id="content">${renderBody(r)}</main>${footer}<a class="whatsapp-float" href="https://wa.me/905378896885" aria-label="WhatsApp">◉ WhatsApp</a></body></html>`;
   let localizedPage=page.replace('>◉ WhatsApp</a>',`>${whatsappSvg}<span>WhatsApp</span></a>`);
   const specLabels=locale==='en'?{Uzunluk:'Length',Genişlik:'Width',Yükseklik:'Height'}:{Uzunluk:'الطول',Genişlik:'العرض',Yükseklik:'الارتفاع'};
   for(const [source,label] of Object.entries(specLabels))localizedPage=localizedPage.replaceAll('<li>'+source+':','<li>'+label+':');
   const dest=path.join(root,locale,...r.split('/'));fs.mkdirSync(dest,{recursive:true});fs.writeFileSync(path.join(dest,'index.html'),localizedPage);
  }
 }
}
