// Full editorial translations for all long-form guides. Each section preserves the
// source article's practical cautions and product-specific details.
export const localizedGuides = {
en: {
  'kuruyemis-kavurma-makinesi-secimi': {title:'How to Choose a Nut Roasting Machine: Questions to Ask',seoTitle:'How to Choose a Nut Roasting Machine',desc:'A buying guide to product recipes, verified line output, heat source, cleaning and service conditions when choosing a nut roaster.',sections:[
    ['Describe the production conditions, not just the product','The fact that one machine can process hazelnuts, almonds, peanuts and seeds does not mean one setting will suit them all. Include particle-size distribution, incoming moisture, shell condition and target colour in the enquiry. Where possible, request a trial using a representative raw-material sample. This lets you discuss the result achieved with your product instead of relying on a general catalogue capacity.'],
    ['Convert nominal capacity into usable output','Ask which product, starting moisture and target result support the machine’s hourly-output claim. Then ask how many kilograms of conforming product will be ready at the end of a shift after changeovers, warm-up, stops, cleaning and cooling. If packaging is slower, a larger roaster alone will not increase total plant output.'],
    ['Compare these items in every quotation','List the heat source and required utilities, feeding method, controls and recipe storage, cooling, dust and shell handling, maintenance access, spare parts, installation and operator training as separate items. Quotes from different suppliers are comparable only when they cover the same scope.'],
    ['Set acceptance criteria before ordering','Agree on the test raw material, finished-product definition, measurement method, trial duration and acceptance owners in the quotation. Choose indicators such as colour, moisture, breakage and rejects to suit the product. If the measurement method is not written down, the parties may interpret the result differently later.'],
    ['How should you assess Sonsuz Makina models?','HT 15, HT 30, HT 75, HT 150, HT 500, HT 750 and HT 1000 are listed in the same model family; do not treat a model number by itself as a verified hourly-capacity guarantee. Request a current technical sheet and an assessment using your own raw material.']
  ]},
  'kavurma-ve-kurutma-arasindaki-fark': {title:'Roasting and Drying: Two Different Production Goals',seoTitle:'Roasting vs Drying for Nuts',desc:'Compare the distinct process goals of drying and roasting, including moisture, colour, flavour, energy and finished-product control.',sections:[
    ['Separate the purpose of each process','Drying focuses on controlling moisture; roasting develops flavour, aroma and colour. Even when one machine can perform both tasks, define the incoming conditions and desired output separately. A hotter process does not automatically produce a better roast.'],
    ['Set measurement points in advance','Record when inlet and outlet samples will be taken, how moisture will be measured and how colour will be assessed. Comparisons based only on an operator’s visual judgement are difficult to reproduce across shifts and batches.'],
    ['Include cooling in the line design','The product’s journey does not end when heat treatment is complete. Cooling and holding time can affect how the product behaves during packaging. Plan the roaster’s target output together with cooling and packaging speeds.'],
    ['Run trials with your own raw material','A result obtained with another producer’s product cannot be transferred directly to your incoming moisture and particle size. Before accepting an offer, compare several settings with representative samples and retain the approved result with a written recipe and measurement notes.'],
    ['Match the machine to the process goal','When reviewing HT-series roasting and drying models, state the product and the result you want to achieve. Confirm current technical limits and energy requirements with the manufacturer.']
  ]},
  'findik-kavurma-makinesi-secimi': {title:'Hazelnut Roasting Machine: How to Specify One',desc:'A practical guide to hazelnut samples, roast profile, shell condition and made-to-order technical review.',sections:[
    ['Describe the hazelnuts you process','Share the size distribution, whether the nuts are in-shell or kernels, incoming moisture and preparation method. Raw materials sold under the same name can behave differently. A representative sample gives the manufacturer a more useful basis for review than a general catalogue description.'],
    ['Make the target roast profile specific','Describe the expected colour, crunch, aroma and end use. Hazelnuts for retail snacks, bakery ingredients or coating may need different finished-product criteria. A sample or written quality target helps the parties plan a meaningful recipe trial.'],
    ['Discuss shell handling and breakage','If roasting in-shell hazelnuts, clarify expectations for cracking and later separation. For kernels, whole-kernel integrity and breakage are important quality considerations. Confirm how feeding, roasting and cooling will handle the product within the quotation scope.'],
    ['Request a sample trial and layout review','Discuss a trial using representative raw material and which settings will be recorded. Before ordering, confirm door access, installation footprint, utility connections, ventilation and operator access on a current drawing.'],
    ['Compare made-to-order quotes on equal scope','The quotation should identify the machine configuration, included equipment, installation responsibilities, current technical drawing and acceptance method. When comparing hazelnut roaster prices, make sure each supplier has received the same sample details and target profile.']
  ]},
  'kuruyemis-uretim-hatti-planlama': {title:'How to Plan a Nut Processing Line',desc:'Plan feeding, roasting, cooling, screening, seasoning and packaging around real production bottlenecks.',sections:[
    ['Map the product flow first','Show receiving, storage, pre-screening, roasting or drying, cooling, sorting, seasoning and packaging in a single flow diagram. Note the input and output form at each stage. This is a more useful starting point than looking at each machine’s capacity in isolation.'],
    ['Calculate the bottleneck by shift','The slowest required operation determines line output. Matching roaster capacity to packaging speed is not enough: include changeovers, cleaning and planned downtime. Express the target as conforming product packaged during one shift.'],
    ['Design the layout around more than machine dimensions','Allow room for operator routes, service doors, cleaning, product and packaging movement, and waste removal. Check existing electrical and fuel infrastructure, ventilation and possible future expansion on the layout drawing.'],
    ['Break the quotation into scope items','Ask suppliers to list machinery, feeding and transfer equipment, cooling, automation, installation, training and commissioning separately. A component omitted from the initial offer can make an apparently cheaper proposal more expensive overall.'],
    ['Prepare three production scenarios','Create separate scenarios for today’s products and shifts, expected growth and different product recipes. Mark the slowest station in each scenario and identify the conditions under which the investment will actually increase capacity.']
  ]},
  'kuruyemis-kavurma-makinesi-fiyati': {title:'Nut Roaster Prices: How to Compare Quotations',desc:'Clarify scope, capacity, energy, automation and commissioning before comparing nut-roaster quotations.',sections:[
    ['Why can a single price be misleading?','Two roasters sold under the same name may differ in feeding, heating, controls, cooling and service scope. An online price is therefore not the cost of a line installed at your plant. Start by documenting the products, target output, site layout and available utilities together.'],
    ['Divide the offer into four parts','Review the machine itself; auxiliary equipment and connections; installation and commissioning; and operating and maintenance costs. Make exclusions visible, including transport, operator training, an initial spare-parts kit and warranty conditions. Compare total cost of ownership, not just the purchase price.'],
    ['Question the stated capacity','The required figure should describe acceptable finished product, not only the machine’s theoretical throughput. Ask which raw material and recipe were used to measure catalogue capacity. Request a separate shift-output estimate that includes changeovers and cleaning.'],
    ['Choose energy and automation deliberately','The heat source depends on site infrastructure and the planned production schedule. Assess automation through recipe repeatability, operator workload and record-keeping needs rather than simply counting features. Show the capital and operating impact of each option as separate quotation lines.'],
    ['Request comparable proposals','Give every supplier the same product list, sample properties, shift target, installation space and acceptance criteria. Mark included and excluded work in each offer. This prevents an option that omits cooling or commissioning from appearing better value by mistake.']
  ]},
  'istege-gore-kuruyemis-kavurma-makinesi': {title:'Custom Nut Roasting Machine: Made to Order',desc:'Specify a nut roaster around your product, roast profile, site conditions and technical drawing.',sections:[
    ['Describe the requirement, not a standard capacity','Start with the product and desired result. The way hazelnuts, almonds, peanuts or seeds are processed, the target colour and texture, product changes and downstream steps all inform the configuration. A model name alone does not establish suitability for your process.'],
    ['Use a sample and recipe','Where possible, share a representative raw-material sample and an example of the finished product. Review the current recipe, desired roast profile, cooling and the product’s next step in the plant together. This helps shape an enquiry around your actual material rather than generic assumptions.'],
    ['Include site conditions early','Installation footprint, doors and handling route, electrical or fuel connections, ventilation and operator access belong in the technical review. A simple layout and photos of the existing line can speed up the first discussion; confirm the current drawing before ordering.'],
    ['Clarify the manufacturing scope','Ask which feeding, cooling, controls, connection equipment, installation and commissioning items are included. Record exclusions and each party’s responsibilities in writing so the delivery scope is clear.'],
    ['Agree on trials and acceptance','Before ordering, define the test material, finished-product target, measurement method and acceptance process together. A sample trial and current technical drawing make a made-to-order machine easier to assess. Confirm technical performance and delivery details with the manufacturer in writing.']
  ]},
  'kuruyemis-uretim-hatti-kurulum-maliyeti': {title:'How to Estimate the Cost of Setting Up a Nut Processing Line',desc:'A capital-planning guide that includes feeding, cooling, packaging, layout, utilities and commissioning beyond the machine price.',sections:[
    ['Define the product and how it will be sold','Will the line process one product or several nuts? Will the finished product be sold in bulk or retail packs? These choices change the process flow and equipment list. Without them, there is no single reliable figure for “plant cost”.'],
    ['Build the equipment list around the process','Separate required and optional items for raw-material receiving and feeding, pre-screening, heat treatment, cooling, sorting, seasoning, weighing and packaging. State the target net output for each station. Identify transfer and connection equipment missing from a supplier’s offer.'],
    ['Budget for site work separately','Electrical panels and distribution, fuel infrastructure, ventilation, space changes, workplace safety and cleaning requirements should be planned separately from the machine price. Do not combine an installation in an existing plant and a new-building project in the same budget assumption.'],
    ['Include commissioning and operation','List transport, installation, initial recipe trials, operator training, a maintenance plan and starting spare-parts needs. Use your actual shift schedule to estimate energy and labour costs. Do not base the investment decision solely on the purchase price.'],
    ['Prepare a three-scenario budget','Create scopes for a basic line, a line ready for growth and a flexible line for different products. Show expected net output, required floor area and missing components for each. If investment is staged, this reveals which equipment can be deferred.']
  ]},
  'leblebi-uretim-hatti-makineleri': {title:'Roasted Chickpea Production Line: Equipment and Process Sequence',seoTitle:'Roasted Chickpea Production Line',desc:'Assess chickpea preparation, heating, moistening, roasting, screening and packaging as one integrated line.',sections:[
    ['Classify the incoming raw material','Chickpea size, moisture and batch consistency affect settings downstream. Do not expect one machine recipe to suit every batch without recording the raw-material properties. Identify any pre-screening and separation needs at the intake stage.'],
    ['Place preparation operations in the flow','The target product determines whether steps such as heating, moistening and dipping are needed. Although these stations may look like separate purchase items, line speed and transfer method should be designed together. Relevant equipment appears on separate product pages in the Sonsuz Makina catalogue.'],
    ['Specify roasting and resting conditions','Target colour and texture are key process outputs. Conditions should be validated for the chickpea batch and intended product. During a trial, keep the inlet and outlet samples, processing time and operator notes together in one record.'],
    ['Measure screening and packaging bottlenecks','Even with high roaster output, slower screening, sorting or filling reduces usable shift output. Measure conforming product separately at each station. Include rejects and rework flow in the layout plan.'],
    ['Request a process diagram with the quotation','The written offer should state which machines are included, how product transfers between stations, and the space and energy requirements. Do not infer a complete line from machine names alone; confirm scope with a drawing and acceptance plan.']
  ]},
  'kuruyemis-paketleme-makinesi-gramaj-secimi': {title:'Nut Packaging Machines: Choosing Pack Weight and Weighing Heads',desc:'Compare semi-automatic and automatic filling options by pack weight, product fragility, target count and line flow.',sections:[
    ['Do not treat the weight range as one number','Record the smallest and largest pack sizes as well as the weights that account for most sales. If the line will pack different nuts or mixes, assess each product’s flow and breakage behaviour separately. This avoids choosing a machine only because it can handle the extreme sizes.'],
    ['Connect packs per minute to the shift plan','Use the daily sales plan to estimate pack count and shift time. Reduce available production time for film changes, product changes, weight checks and cleaning. Keep theoretical packs per minute separate from the accepted net pack count.'],
    ['Interpret the number of weighing heads correctly','Two-, four- or five-head designs may suit different weighing and feeding needs; more heads do not automatically produce a better result in every application. Test accuracy, product fragility, target weight and feeding arrangement together.'],
    ['Include work around the filler','Mark feeding, pack format, sealing, date coding, check-weighing and case preparation in the quotation scope. The phrase “packaging machine” does not mean all of this equipment is included.'],
    ['Set up acceptance tests with samples','Include the most frequently packed products and weights in the test list. Record target-weight accuracy, breakage, faulty packs, product-change time and operator intervention. Verify final performance with the actual product and packaging.']
  ]},
  'elektrikli-dogalgazli-kavurma-makinesi-secimi': {title:'Electric or Gas Roasting? Choosing a Heat Source',desc:'Choose between electric and gas roasting by considering site utilities, operating profile, process control and total running cost.',sections:[
    ['Check the available site infrastructure first','Record the electrical connection and load capacity, gas access, ventilation and installation constraints. Choosing only by energy-unit price can overlook connection, permitting and site-installation work.'],
    ['Keep the comparison conditions consistent','Assess both options using the same raw material, incoming moisture, target finished product and net shift output. Comparing one system’s rated power with the other’s measured consumption will not give a sound result. Ask the supplier for the test conditions and measurement method.'],
    ['Allow for part-load use and changeovers','The machine may not run at full capacity continuously. Ask how warm-up, standby, recipe changes and stops affect the energy calculation. Your assumed usage profile should reflect the actual shift schedule.'],
    ['Put investment and operating costs in one table','Show machine and utility investment, energy, maintenance, spare parts and potential downtime on separate lines. Date and state the units for energy-price assumptions so the calculation can be updated when prices change.'],
    ['Complete the decision using site-specific conditions','Request a current technical quotation using the product, capacity target and existing site details. Confirm separately with the manufacturer whether each heating option suits the selected Sonsuz Makina model and configuration.']
  ]},
  'draje-kaplama-makinesi-secimi': {title:'Choosing a Coating Machine: Pan, Product and Batch Plan',desc:'Define the product core, coating goal, pan type, cleaning and batch flow before investing in a coating machine.',sections:[
    ['Identify the product to be coated','Almonds, hazelnuts and other centres can differ in size, surface behaviour and fragility. Do not group sugar, chocolate and other coating goals under one generic recipe. State the product and desired finish clearly in the enquiry.'],
    ['Read batch volume together with cycle time','Pan volume alone does not tell you daily output. Define a full cycle that includes loading, coating, intermediate drying or holding, unloading and cleaning. Plan the shift target using the number of cycles that can actually be completed.'],
    ['Ask about materials and cleaning access','Technical evaluation should cover product-contact surfaces, cleaning method, changeover time between products and maintenance access. Where different coatings are used, cross-contamination controls belong in the operating plan.'],
    ['Compare single and double pans on equal scope','The benefits of multiple pans depend on the product mix and shift pattern. Show auxiliary equipment, feeding, discharge and operator requirements in the same quotation table. Do not infer capacity from pan count alone.'],
    ['Document the sample trial','Use a representative product to assess acceptable coating appearance, breakage, rejects and cycle time. State in the offer and acceptance plan that actual performance depends on product, recipe and installation conditions.']
  ]},
  'kahve-kavurma-makinesi-secimi': {title:'Choosing a Coffee Roaster: Batch, Profile and Production Flow',desc:'Assess batch planning, profile repeatability, cooling and operating flow together when investing in coffee roasting.',sections:[
    ['Distinguish the search term correctly','“Industrial coffee machine” can also refer to beverage-preparation equipment. For a bean-roasting investment, specify “coffee roaster” and the intended batch pattern. This guide does not cover espresso or serving machines.'],
    ['Connect batch targets to daily output','Warm-up, roasting, discharge, cooling and product changes matter as much as batch size. State the target as daily roasted-bean output. Do not derive shift capacity from a single batch figure.'],
    ['Ask how profiles are repeated','The supplier should demonstrate how temperature and time are recorded, which settings the operator can adjust and how a recipe is repeated on the next batch. During trials, record bean type and starting conditions.'],
    ['Plan cooling and the next operation','After roasting, cooling, holding, grinding or packaging depends on the product strategy. Consider the speed and space requirements of these stations alongside the roaster choice.'],
    ['Verify technical suitability','The Sonsuz Makina e-catalogue lists a coffee-roasting model under code HT 30 CR; the website product code has been aligned with the catalogue. Request a current technical sheet and a trial with representative beans to confirm the heating, control options and site suitability.']
  ]},
  'bantli-donerli-kavurma-makinesi-secimi': {title:'Belt-Type or Rotary Nut Roaster? A Selection Guide',seoTitle:'Belt or Rotary Nut Roaster?',desc:'Compare belt-type and rotary roasting machines through product trials, plant layout, technical drawings and quotation scope.',sections:[
    ['Match the machine type to the product goal first','The Sonsuz Makina e-catalogue lists belt-type and rotary-type roasting machines in separate groups. The machine name alone does not establish product suitability or the expected result. Describe the product, shell condition, desired colour and texture, product-change frequency and next process steps in the same enquiry.'],
    ['Use a sample trial as a selection criterion','Prepare a representative raw-material sample and an example of the acceptable finished product. Agree with the manufacturer in advance which settings and outcomes will be recorded during the trial. Do not treat a general description that has not been checked with your sample as a purchase guarantee.'],
    ['Compare the layout with the current technical drawing','Overall dimensions in the e-catalogue can support an initial space check. Confirm doors and transport routes, operator access, cleaning and maintenance clearances, and existing line connections against the current order drawing. Do not assume catalogue dimensions are the final external dimensions of a made-to-order machine.'],
    ['Ask about heating and auxiliary systems together','Use the heating types and technical values shown for each catalogue model as a starting reference. List electrical or fuel connections, ventilation, feeding, cooling and transfer needs separately in the quotation. Confirm final suitability against site conditions and the current technical sheet.'],
    ['Compare quotations on the same scope','Compare the machine, included equipment, installation responsibilities, delivery, training and trial acceptance criteria for both options under the same headings. A trial with your product and a made-to-order technical drawing should form the basis of the decision.']
  ]},
  'denizli-kuruyemis-makinesi-imalati': {title:'Nut Processing Machinery Made in Denizli: What to Include in an Enquiry',seoTitle:'Nut Machinery Manufacturer in Denizli',desc:'For businesses seeking a nut roasting machine manufacturer in Denizli, a practical guide to defining requirements, technical discussions, samples and made-to-order quotations.',sections:[
    ['Describe the need before choosing a machine name','State the product to be processed, the roasting result you want, the current production steps and where the new machine will fit in the line. Machine type should follow these details; a general product label alone cannot establish suitability.'],
    ['Confirm current technical information together','The Sonsuz Makina e-catalogue lists different machine families and models. Share the model code of interest, plant layout and available connections. Dimensions and configuration should be confirmed against the current made-to-order technical drawing.'],
    ['Discuss samples and acceptance criteria early','Where possible, include a representative product sample and an example of the result you expect. If a trial is planned, agree in writing which characteristics will be evaluated and how the result will be recorded. Treat unverified performance claims as unconfirmed until tested.'],
    ['Compare quotations on the same scope','Request separate details for machine scope, auxiliary equipment, site connections, delivery and installation responsibilities, training and acceptance steps. This makes it easier to compare what each supplier includes.'],
    ['Prepare for a meeting in Denizli','Sonsuz Makina is located at Gida ve Toptancilar Sitesi, 7133 Sokak No: 5, Bozburun Mahallesi, Merkezefendi, Denizli. For an initial discussion, share the product, intended result, available layout information and any catalogue model you have in mind.']
  ]},
  'kuruyemis-kavurma-makinesi-teklif-talebi': {title:'Nut Roasting Machine Quote: What Information Should You Send?',seoTitle:'Nut Roasting Machine Quote Checklist',desc:'Prepare a useful quote request for a nut roaster with this checklist for product, target result, plant, machine type and order scope.',sections:[
    ['Describe the product and the result you want','Name the product to be processed, how it is currently prepared and the roast characteristics you expect. Process requirements can change with the product, so list each product separately if you plan to process more than one. Where possible, provide a representative raw-material sample and an example of the expected finished product.'],
    ['Do not treat a machine type as a final decision by itself','You can mention that you are considering a belt-type or rotary system, but assess the final choice together with product trials, process expectations and site conditions. A machine name alone does not confirm product suitability or the result.'],
    ['Share plant information and layout','Provide installation-area dimensions, doors and transport routes, existing equipment connections, access to power or fuel, and ventilation conditions. A sketch or photo of the current line can make an initial technical discussion more efficient. Confirm final dimensions against the current order drawing.'],
    ['Ask for the quotation scope item by item','Request separate details for the machine and auxiliary equipment included, responsibility for site connections, delivery and installation scope, training and acceptance steps. This lets you compare different quotations on the same scope.'],
    ['A short request template you can send','Fill in: “Product to process: … / Desired result: … / Machine type or catalogue model considered: … / Current plant and line details: … / Sample or drawing available: … / Scope items to clarify in the quote: …” Do not guess technical details you do not know; confirm them with the manufacturer.']
  ]},
  'kuruyemis-kavurma-makinesi-teknik-cizim-kontrolu': {title:'Nut Roasting Machine Drawing: Pre-Order Checklist',seoTitle:'Nut Roaster Technical Drawing Guide',desc:'A practical guide to checking dimensions, transport routes, connections and maintenance access on a nut roasting machine drawing before ordering.',sections:[
    ['Separate catalogue dimensions from the order drawing','E-catalogue dimensions are useful for an initial review. Confirm the made-to-order machine’s external dimensions, connection points and options in writing against the current technical drawing. Do not treat a drawing for an earlier model or catalogue as the final approval document.'],
    ['Check how the machine will enter the plant','Review not only the installation footprint but also unloading from the delivery vehicle, doors and corridor clearances, turning space and movement during installation. Compare measurements with the plant manager and manufacturer on the same drawing.'],
    ['Mark the connections to the production line','Show the product-feed and discharge directions, upstream and downstream equipment, operator workspace and points that intersect with the existing line. If a connection or direction is unclear, ask the technical team before approving manufacture.'],
    ['Confirm power, fuel and ventilation notes','Use the heating option stated in the catalogue and drawing to verify the site’s electrical or fuel connections, ventilation and flue requirements with the responsible specialists. Do not make assumptions before confirming exact technical values against the current machine sheet and plant design.'],
    ['Put cleaning, maintenance and acceptance in writing','Ask about access for daily cleaning and scheduled maintenance, removable parts and service approach. Ensure the approval drawing has a revision date and sign-off from both parties. If a product-sample trial is planned, include acceptance criteria separately in the quotation.']
  ]},
  'kuruyemis-kavurma-makinesi-numune-denemesi': {title:'Nut Roaster Trial: Sample and Acceptance Criteria',seoTitle:'Nut Roasting Machine Sample Trial',desc:'Assess a machine offer using your own product: prepare a representative sample, record the trial and agree on written acceptance criteria before ordering.',sections:[
    ['Choose a representative sample, not the best-looking nuts','Use a sample that reflects the batch you expect to process. Record the product, shell condition, any pre-treatment and batch date. A handful of selected, flawless pieces may not show how the machine behaves with ordinary production material. Agree the sample quantity and packing method with the supplier before sending it.'],
    ['Make “a good roast” specific','Describe the colour, texture and aroma you want, and show an example or photo of defects you will not accept. If moisture or colour is measured, agree on the instrument, sampling point and timing, and who records the result. A visual check can help too, provided lighting, cooling time and the comparison sample are consistent.'],
    ['Record what changed during the trial','Ask the supplier to note which settings were changed and when. Keep incoming product condition, machine settings, processing time, output observations and any stops in one record. If several products or recipes are tried, record them separately instead of averaging their results together.'],
    ['Review the cooled product and the next step','A hot sample may look or feel different after it cools. Agree when to assess it and, if it will be packed, when to check it in the package. If breakage, screening loss or packing behaviour matters, include those checks in the trial; a roaster test alone does not validate the whole line.'],
    ['Put acceptance conditions in the order documents','State the test material, target product characteristics, measurement method, conditions for a repeat trial and each party’s responsibilities. Replace vague wording such as “sample approved” with the actual result and the conditions under which it was achieved. Confirm whether a sample trial is available and what it includes; this guide does not assume every manufacturer provides the same service.']
  ]},
  'kuruyemis-eleme-makinesi-secimi': {title:'How to Choose a Nut Screening Machine: What to Compare',seoTitle:'Nut Screening Machine Selection Guide',desc:'Compare nut screening offers by product sample, target fractions, good-product loss and production-line connections.',sections:[
    ['Start by defining what needs to be separated','Sizing, removing broken pieces and removing foreign material are different objectives. Describe what should remain in the product and what should leave it. If you need several grades, name each output fraction. This makes the offer about the job to be done, rather than the generic name “screening machine.”'],
    ['Show the supplier the product and target grades','Where possible, provide a sample from a normal production batch and examples of each desired fraction. Do not choose an opening based only on the product name: size, shape, fragility and variation in the incoming mix can affect the result. If a trial is unavailable, ask what evidence the selection will be based on.'],
    ['Measure loss of acceptable product as well','Looking only at the rejected material leaves out half the picture. Record how much acceptable product goes to the wrong outlet and how much unwanted material remains in the main product. Agree on quantities and sampling method beforehand. Without these records, broad claims such as “clean separation” do not make competing offers comparable.'],
    ['Ask about cleaning, changeovers and the actual line','Ask how settings or screens change between products, what areas are reached during cleaning, and how stoppages or blockages are recorded. These details vary by model and should be checked against the current drawing or machine demonstration. Also consider the operating pattern of the roasting step before the screen and packaging after it.'],
    ['Close the quotation with product-specific acceptance terms','List the tested product and batch, target fractions, acceptable product loss, measurement method, included equipment and plant connections. If several products are planned, do not assume that testing one proves suitability for all. Review Sonsuz Makina’s screen and sorting-belt options, then confirm model suitability with a project-specific technical discussion.']
  ]}
},
ar: {
  'kuruyemis-kavurma-makinesi-secimi': {title:'كيفية اختيار آلة تحميص المكسرات: أسئلة ينبغي طرحها',seoTitle:'كيفية اختيار آلة تحميص المكسرات',desc:'دليل شراء يشرح وصفات المنتج والإنتاج الفعلي ومصدر الحرارة والتنظيف والخدمة عند اختيار محمصة المكسرات.',sections:[
    ['صف ظروف الإنتاج لا اسم المنتج فقط','إمكانية استخدام الآلة نفسها للبندق واللوز والفول السوداني والبذور لا تعني أن إعداداً واحداً يناسبها جميعاً. أدرج توزيع أحجام الحبات ورطوبة المادة الخام وحالة القشرة واللون المستهدف في طلب العرض. واطلب، إن أمكن، تجربة عينة ممثلة من خامتك. عندها تناقش النتيجة على منتجك بدلاً من الاكتفاء بطاقة عامة في الكتالوج.'],
    ['حوّل الطاقة الاسمية إلى إنتاج فعلي صالح','اسأل عن المنتج ورطوبته الأولية والنتيجة التي بُني عليها ادعاء الإنتاج بالساعة. ثم اسأل عن كمية المنتج المطابق للمواصفات التي ستبقى في نهاية الوردية بعد تبديل المنتجات والإحماء والتوقف والتنظيف والتبريد. إذا كانت التعبئة أبطأ، فلن ترفع المحمصة الأكبر وحدها إنتاج المصنع الكلي.'],
    ['قارن البنود نفسها في كل عرض','اطلب إدراج مصدر الحرارة والمرافق المطلوبة وطريقة التغذية والتحكم وحفظ الوصفات والتبريد ومعالجة الغبار والقشور وإمكانية الصيانة وقطع الغيار والتركيب وتدريب المشغل كبنود منفصلة. لا تكون عروض الموردين قابلة للمقارنة إلا إذا شملت النطاق نفسه.'],
    ['حدد معايير القبول قبل الطلب','اتفق في العرض على خامة الاختبار وتعريف المنتج النهائي وطريقة القياس ومدة التجربة والمسؤولين عن القبول. اختر مؤشرات مثل اللون والرطوبة والكسر والهدر بحسب المنتج. إذا لم تُكتب طريقة القياس فقد يفسر الطرفان النتيجة لاحقاً بطريقتين مختلفتين.'],
    ['كيف تقيّم طرازات سونوز ماكينة؟','تُدرج الطرازات HT 15 وHT 30 وHT 75 وHT 150 وHT 500 وHT 750 وHT 1000 ضمن عائلة واحدة؛ لا تعتبر رقم الطراز وحده ضماناً لإنتاج مؤكد بالساعة. اطلب ورقة فنية حديثة وتقييماً باستخدام خامتك.']
  ]},
  'kavurma-ve-kurutma-arasindaki-fark': {title:'التحميص والتجفيف: هدفان مختلفان للإنتاج',seoTitle:'التحميص أم التجفيف للمكسرات؟',desc:'قارن بين هدفي التجفيف والتحميص من حيث الرطوبة واللون والنكهة والطاقة وضبط المنتج النهائي.',sections:[
    ['ميّز هدف كل عملية','يركز التجفيف على التحكم في الرطوبة، بينما يهدف التحميص إلى تطوير النكهة والرائحة واللون. حتى إذا أمكن للآلة نفسها تنفيذ المهمتين، ينبغي تعريف ظروف الدخول والخصائص المطلوبة عند الخروج لكل منهما. فالمعالجة بدرجة حرارة أعلى لا تعني تلقائياً تحميصاً أفضل.'],
    ['حدد نقاط القياس مسبقاً','سجّل وقت أخذ عينات الدخول والخروج وطريقة قياس الرطوبة وكيفية تقييم اللون. يصعب تكرار المقارنة بين الورديات والدفعات إذا اعتمدت على الملاحظة البصرية للمشغل وحدها.'],
    ['لا تنس التبريد في تصميم الخط','لا تنتهي رحلة المنتج على الخط بانتهاء المعالجة الحرارية. فقد يؤثر التبريد ووقت الانتظار في سلوك المنتج أثناء التعبئة. خطط لإنتاج المحمصة المستهدف مع سرعة التبريد والتعبئة معاً.'],
    ['أجر التجارب على خامتك','لا يمكن نقل نتيجة منتج مورد آخر مباشرة إلى رطوبة خامتك وحجم حباتها. قارن عدة إعدادات بعينات ممثلة قبل قبول العرض، واحتفظ بالنتيجة المعتمدة مع وصفة مكتوبة وملاحظات القياس.'],
    ['طابق الآلة مع هدف المعالجة','عند مراجعة طرازات التحميص والتجفيف من سلسلة HT، اذكر المنتج والنتيجة التي تريدها. أكّد الحدود الفنية الحالية ومتطلبات الطاقة مع الشركة المصنعة.']
  ]},
  'findik-kavurma-makinesi-secimi': {title:'اختيار محمصة البندق: كيف تحدد المواصفات؟',desc:'دليل عملي لعينات البندق وملف التحميص وحالة القشرة والتقييم الفني للتصنيع حسب الطلب.',sections:[
    ['صف حالة البندق الذي تعالجه','شارك توزيع الأحجام وما إذا كان البندق بقشره أو لبه ورطوبته عند الدخول وطريقة التحضير. قد تتصرف المواد الخام المباعة بالاسم نفسه بطرق مختلفة. تمنح العينة الممثلة المصنع أساساً فنياً أفضل من الوصف العام في الكتالوج.'],
    ['حدد ملف التحميص المطلوب','صف اللون والقرمشة والرائحة والاستخدام النهائي المتوقع. قد تختلف معايير المنتج النهائي للبندق المخصص للبيع كوجبة خفيفة أو لمكونات المخبوزات أو للتغطية. تساعد العينة أو مواصفات الجودة المكتوبة في تخطيط تجربة وصفة مفيدة.'],
    ['ناقش التعامل مع القشرة والكسر','إذا كان التحميص للبندق بقشره، وضح توقعات التشقق والفصل اللاحق. أما في اللب، فسلامة الحبات الكاملة والكسر من اعتبارات الجودة المهمة. أكّد ضمن نطاق العرض كيفية التعامل مع المنتج أثناء التغذية والتحميص والتبريد.'],
    ['اطلب تجربة عينة ومراجعة التخطيط','ناقش تجربة بمادة خام ممثلة والإعدادات التي ستُسجل. وقبل الطلب، تحقق على رسم حديث من المداخل ومساحة التركيب والوصلات والتهوية وإمكانية وصول المشغل.'],
    ['قارن عروض التصنيع حسب الطلب بنطاق موحد','ينبغي أن يوضح العرض تكوين الآلة والمعدات المشمولة ومسؤوليات التركيب والرسم الفني الحالي وطريقة القبول. عند مقارنة أسعار محمصات البندق، تأكد من أن كل مورد تلقى وصف العينة وملف التحميص المستهدف نفسيهما.']
  ]},
  'kuruyemis-uretim-hatti-planlama': {title:'كيفية تخطيط خط لمعالجة المكسرات',desc:'خطط للتغذية والتحميص والتبريد والغربلة والتتبيل والتعبئة على أساس اختناقات الإنتاج الفعلية.',sections:[
    ['ارسم تدفق المنتج أولاً','اعرض الاستلام والتخزين والغربلة الأولية والتحميص أو التجفيف والتبريد والفرز والتتبيل والتعبئة في مخطط واحد. سجّل شكل المنتج عند دخول كل مرحلة وخروجه منها. هذه بداية أنفع من النظر إلى طاقة كل آلة منفردة.'],
    ['احسب عنق الزجاجة لكل وردية','تحدد أبطأ عملية ضرورية إنتاج الخط. ولا يكفي جعل طاقة التحميص مساوية لسرعة التعبئة؛ أدرج تبديل المنتجات والتنظيف والتوقف المخطط. عبّر عن الهدف بكمية المنتج المطابق للمواصفات والمعبأ خلال الوردية.'],
    ['خطط للموقع بما يتجاوز أبعاد الآلة','خصص مساحة لمسار المشغل وفتحات الصيانة والتنظيف وحركة المنتج والعبوات وإخراج النفايات. افحص على الرسم البنية الكهربائية والوقود والتهوية وإمكانية التوسع مستقبلاً.'],
    ['قسّم نطاق العرض إلى بنود','اطلب إدراج الآلات ومعدات التغذية والنقل والتبريد والأتمتة والتركيب والتدريب والتشغيل الأولي بصورة منفصلة. فقد يجعل عنصر محذوف العرض الأرخص ظاهرياً أعلى تكلفة عند اكتمال المشروع.'],
    ['أعد ثلاثة سيناريوهات للإنتاج','أنشئ سيناريو للإنتاج والورديات الحالية، وآخر للنمو المتوقع، وثالث لوصفات منتجات مختلفة. حدّد أبطأ محطة في كل سيناريو واعرف الظروف التي سيزيد الاستثمار عندها الطاقة فعلاً.']
  ]},
  'kuruyemis-kavurma-makinesi-fiyati': {title:'أسعار محمصات المكسرات: كيف تقارن عروض الأسعار؟',desc:'حدّد النطاق والطاقة والوقود والأتمتة والتشغيل الأولي قبل مقارنة عروض محمصات المكسرات.',sections:[
    ['لماذا قد يكون السعر الواحد مضللاً؟','قد تختلف آلتان تحملان الاسم نفسه في التغذية والتسخين والتحكم والتبريد والخدمات المشمولة. لذلك لا يمثل سعر الإنترنت تكلفة خط مركب في مصنعك. ابدأ بتوثيق المنتجات والإنتاج المستهدف ومخطط الموقع والمرافق المتاحة في ملف واحد.'],
    ['قسّم العرض إلى أربعة أجزاء','راجع الآلة نفسها، والمعدات المساعدة والتوصيلات، والتركيب والتشغيل الأولي، ومصاريف التشغيل والصيانة. أظهر بوضوح ما لا يشمله العرض مثل النقل وتدريب المشغل ومجموعة قطع الغيار الأولية وشروط الضمان. قارن التكلفة الكلية للامتلاك لا سعر الشراء وحده.'],
    ['استوضح معنى الطاقة المذكورة','ينبغي أن يصف الرقم المطلوب المنتج النهائي المقبول، لا التدفق النظري للآلة فقط. اسأل عن الخامة والوصفة المستخدمتين لقياس طاقة الكتالوج. واطلب حساباً منفصلاً لإنتاج الوردية يشمل تبديل المنتجات والتنظيف.'],
    ['اختر الوقود والأتمتة عن قصد','يعتمد مصدر الحرارة على مرافق الموقع وجدول الإنتاج المخطط. قيّم الأتمتة من خلال تكرار الوصفة وعبء المشغل والحاجة إلى تسجيل البيانات، لا بعدد الخصائص وحده. أظهر أثر كل خيار في الاستثمار والتشغيل كبند مستقل.'],
    ['اطلب عروضاً قابلة للمقارنة','أرسل إلى كل مورد قائمة المنتجات وخصائص العينات وهدف الوردية ومساحة التركيب ومعايير القبول نفسها. وعلّم الأعمال المشمولة والمستثناة في كل عرض. يمنع ذلك اعتبار خيار ناقص التبريد أو التشغيل الأولي أفضل قيمة بالخطأ.']
  ]},
  'istege-gore-kuruyemis-kavurma-makinesi': {title:'محمصة مكسرات حسب الطلب',desc:'حدد مواصفات المحمصة وفق المنتج ونتيجة التحميص وظروف الموقع والرسم الفني.',sections:[
    ['صف احتياجك بدلاً من سعة قياسية','ابدأ بتحديد المنتج والنتيجة المطلوبة. تؤثر طريقة معالجة البندق واللوز والفول السوداني والبذور واللون والقوام المستهدفان وتبديل المنتجات والخطوات التالية في تكوين الآلة. ولا يكفي اسم الطراز وحده لإثبات ملاءمته لعمليتك.'],
    ['استخدم عينة ووصفة','إن أمكن، أرسل عينة ممثلة من المادة الخام ومثالاً على المنتج النهائي. ناقشوا الوصفة الحالية ودرجة التحميص المطلوبة والتبريد والخطوة التالية للمنتج داخل المصنع. يساعد ذلك في إعداد الطلب وفق منتجك الفعلي بدلاً من افتراضات عامة.'],
    ['أدرج ظروف الموقع مبكراً','ينبغي أن يشمل التقييم الفني مساحة التركيب والأبواب ومسار النقل ووصلات الكهرباء أو الوقود والتهوية وسهولة وصول المشغل. يمكن لمخطط بسيط وصور الخط الحالي تسريع النقاش الأولي؛ أكّد الرسم الفني الحالي قبل الطلب.'],
    ['حدد نطاق التصنيع في العرض','اسأل عن عناصر التغذية والتبريد والتحكم والتوصيل والتركيب والتشغيل الأولي المشمولة. وسجل الاستثناءات ومسؤوليات كل طرف كتابةً حتى يكون نطاق التسليم واضحاً.'],
    ['اتفق على التجربة ومعايير القبول','قبل الطلب، حددوا معاً مادة الاختبار والمنتج النهائي المطلوب وطريقة القياس وإجراءات القبول. تجعل تجربة العينة والرسم الفني الحالي تقييم الآلة المصنّعة حسب الطلب أكثر وضوحاً. ويجب تأكيد الأداء الفني وتفاصيل التسليم مع المصنع كتابةً.']
  ]},
  'kuruyemis-uretim-hatti-kurulum-maliyeti': {title:'كيفية تقدير تكلفة إنشاء خط لمعالجة المكسرات',desc:'دليل استثماري يشمل التغذية والتبريد والتعبئة والموقع والمرافق والتشغيل الأولي إلى جانب سعر الآلة.',sections:[
    ['حدد المنتج وطريقة بيعه','هل سيعالج الخط نوعاً واحداً أم أنواعاً متعددة من المكسرات؟ وهل سيباع المنتج النهائي سائبا أم في عبوات تجزئة؟ يغيّر هذان القراران تدفق الخط وقائمة المعدات. ولا يمكن تحديد رقم موثوق واحد لتكلفة المصنع من دونهما.'],
    ['استخرج قائمة المعدات من تدفق العملية','افصل البنود الضرورية والاختيارية للاستلام والتغذية والغربلة الأولية والمعالجة الحرارية والتبريد والفرز والتتبيل والوزن والتعبئة. اكتب صافي الإنتاج المستهدف لكل محطة. وأظهر معدات النقل والتوصيل غير المدرجة في عرض المورد.'],
    ['ضع ميزانية مستقلة لأعمال الموقع','خطط للوحات والتوزيع الكهربائي وبنية الوقود والتهوية وتعديلات المساحة والسلامة المهنية ومتطلبات التنظيف بصورة منفصلة عن سعر الآلات. ولا تخلط تركيباً في مصنع قائم بمشروع مبنى جديد ضمن افتراض الميزانية نفسه.'],
    ['أدرج التشغيل الأولي والتشغيل اليومي','سجّل النقل والتركيب وتجارب الوصفة الأولية وتدريب المشغل وخطة الصيانة وقطع الغيار الأولية. استخدم جدول الورديات الفعلي لديك لتقدير الطاقة والعمالة. لا تتخذ قرار الاستثمار اعتماداً على سعر الشراء وحده.'],
    ['أعد ميزانية بثلاثة سيناريوهات','أنشئ نطاقاً لخط أساسي وآخر جاهز للنمو وثالثاً مرناً لمنتجات متنوعة. أظهر الإنتاج الصافي المتوقع والمساحة المطلوبة والمكونات الناقصة لكل منها. وإذا كان الاستثمار مرحلياً فسيتضح أي المعدات يمكن تأجيلها.']
  ]},
  'leblebi-uretim-hatti-makineleri': {title:'خط إنتاج الحمص المحمص: المعدات وتسلسل العمليات',seoTitle:'خط إنتاج الحمص المحمص',desc:'قيّم إعداد الحمص والتسخين والترطيب والتحميص والغربلة والتعبئة كخط متكامل.',sections:[
    ['صنّف المادة الخام الواردة','يؤثر حجم حبات الحمص ورطوبتها وثبات الدفعات في إعدادات المراحل التالية. لا تتوقع أن تناسب وصفة آلة واحدة كل الدفعات من دون تسجيل خصائص الخام. حدّد الحاجة إلى الغربلة والفصل الأولي عند الاستلام.'],
    ['أدرج عمليات الإعداد في تدفق الخط','يحدد المنتج المستهدف الحاجة إلى خطوات مثل التسخين والترطيب والتغميس. قد تبدو هذه المحطات بنود شراء مستقلة، لكن ينبغي تصميم سرعة الخط وطريقة النقل بينها معاً. وتظهر المعدات ذات الصلة في صفحات منتجات منفصلة بكتالوج سونوز ماكينة.'],
    ['صف ظروف التحميص والراحة','اللون والقوام المستهدفان من أهم نواتج العملية. يجب التحقق من ظروف التشغيل بحسب دفعة الحمص والمنتج المطلوب. أثناء التجربة، احتفظ بعينتي الدخول والخروج ومدة المعالجة وملاحظات المشغل في سجل واحد.'],
    ['قِس اختناق الغربلة والتعبئة','حتى مع ارتفاع خرج المحمصة، يقل صافي إنتاج الوردية إذا كانت الغربلة أو الفرز أو التعبئة أبطأ. قِس كمية المنتج المطابق في كل محطة على حدة. وأدرج تدفق الهدر وإعادة المعالجة في مخطط الموقع.'],
    ['اطلب مخططاً للعملية مع العرض','يجب أن يوضح العرض المكتوب الآلات المشمولة وطريقة نقل المنتج بين المحطات والمساحة والطاقة المطلوبتين. لا تستنتج وجود خط كامل من أسماء الآلات؛ أكّد النطاق برسم وخطة قبول.']
  ]},
  'kuruyemis-paketleme-makinesi-gramaj-secimi': {title:'آلات تعبئة المكسرات: اختيار وزن العبوة ورؤوس الوزن',desc:'قارن خيارات التعبئة شبه الآلية والآلية وفق وزن العبوة وهشاشة المنتج والعدد المستهدف وتدفق الخط.',sections:[
    ['لا تختزل مجال الأوزان في رقم واحد','سجّل أصغر وأكبر وزن للعبوة، إلى جانب الأوزان الأكثر مبيعاً. وإذا كان الخط سيعبئ أنواعاً أو خلطات مختلفة من المكسرات، فقيّم تدفق كل منتج وسلوكه عند الكسر على حدة. يمنع ذلك اختيار آلة لأنها تتعامل مع الأطراف فقط.'],
    ['اربط العبوات في الدقيقة بخطة الوردية','استخدم خطة المبيعات اليومية لتقدير عدد العبوات ومدة الوردية. اطرح من وقت الإنتاج تبديل الرقائق والمنتج وفحص الوزن والتنظيف. وافصل بين عدد العبوات النظري في الدقيقة والعدد الصافي المقبول.'],
    ['افهم عدد رؤوس الوزن بصورة صحيحة','قد تلائم التصاميم ذات الرأسين أو الأربعة أو الخمسة احتياجات مختلفة للوزن والتغذية؛ فزيادة الرؤوس لا تحسن النتيجة تلقائياً في كل تطبيق. اختبر الدقة وهشاشة المنتج والوزن المستهدف وترتيب التغذية معاً.'],
    ['لا تنس الأعمال المحيطة بآلة التعبئة','أدرج في نطاق العرض التغذية وشكل العبوة والإغلاق وطباعة التاريخ وفحص الوزن وتجهيز الكراتين. فمصطلح «آلة تعبئة» لا يعني أن كل هذه المعدات مشمولة.'],
    ['أنشئ اختبار قبول باستخدام عينات','أدرج المنتجات والأوزان الأكثر تعبئة في قائمة الاختبار. وسجّل دقة الوزن والكسر والعبوات المعيبة ووقت تبديل المنتج وتدخل المشغل. تحقّق من الأداء النهائي باستخدام المنتج والعبوة الفعليين.']
  ]},
  'elektrikli-dogalgazli-kavurma-makinesi-secimi': {title:'التحميص بالكهرباء أم بالغاز؟ اختيار مصدر الحرارة',desc:'اختر بين الكهرباء والغاز بمراعاة مرافق الموقع ونمط التشغيل والتحكم بالعملية والتكلفة الكلية.',sections:[
    ['تحقق أولاً من مرافق الموقع المتاحة','سجّل التوصيل الكهربائي وسعة الأحمال وتوفر الغاز والتهوية وقيود التركيب. فالاختيار وفق سعر وحدة الطاقة وحده قد يغفل التوصيلات والتصاريح وأعمال البنية التحتية.'],
    ['ثبّت شروط المقارنة','قيّم الخيارين باستخدام الخام نفسه ورطوبته الأولية والمنتج النهائي المستهدف وصافي إنتاج الوردية. لا تعطي مقارنة القدرة الاسمية لأحد النظامين بالاستهلاك المقاس للآخر نتيجة سليمة. اطلب من المورد شروط الاختبار وطريقة القياس.'],
    ['احتسب التشغيل الجزئي وتبديل المنتجات','قد لا تعمل الآلة باستمرار عند كامل طاقتها. اسأل عن أثر الإحماء والاستعداد وتبديل الوصفات والتوقف على حساب الطاقة. ينبغي أن يشبه نمط الاستخدام المفترض جدول الورديات الفعلي.'],
    ['اجمع الاستثمار والتشغيل في جدول واحد','أدرج استثمار الآلة والمرافق والطاقة والصيانة وقطع الغيار والتوقف المحتمل في بنود مستقلة. اذكر تاريخ وافتراضات أسعار الطاقة ووحداتها كي يمكن تحديث الحساب عند تغير الأسعار.'],
    ['أكمل القرار وفق ظروف الموقع','اطلب عرضاً فنياً حديثاً باستخدام المنتج والطاقة المستهدفة وبيانات الموقع القائم. وأكّد مع الشركة المصنعة بصورة منفصلة ملاءمة كل خيار تسخين للطراز والتكوين المختارين من سونوز ماكينة.']
  ]},
  'draje-kaplama-makinesi-secimi': {title:'اختيار آلة تغطية الدراجيه: الحوض والمنتج وخطة الدفعات',desc:'حدّد قلب المنتج وهدف التغطية ونوع الحوض والتنظيف وتدفق الدفعات قبل الاستثمار في آلة التغطية.',sections:[
    ['حدد المنتج المراد تغطيته','قد تختلف حبات اللوز والبندق وغيرها في الحجم وسلوك السطح والهشاشة. لا تجمع أهداف التغطية بالسكر أو الشوكولاتة أو غيرهما في وصفة عامة واحدة. اذكر المنتج والطبقة النهائية المطلوبة بوضوح في الطلب.'],
    ['قيّم حجم الدفعة مع زمن الدورة','لا يكشف حجم الحوض وحده الإنتاج اليومي. عرّف دورة كاملة تشمل التحميل والتغطية والتجفيف أو الانتظار الوسيط والتفريغ والتنظيف. وخطط لهدف الوردية على أساس عدد الدورات الممكن إنجازها فعلياً.'],
    ['اسأل عن المواد وسهولة التنظيف','ينبغي أن يشمل التقييم الفني أسطح ملامسة المنتج وطريقة التنظيف ووقت الانتقال بين المنتجات وإمكانية الصيانة. وعند استخدام طبقات مختلفة، ينبغي أن تكون مكافحة انتقال التلوث جزءاً من خطة التشغيل.'],
    ['قارن الحوض المفرد والمزدوج بالنطاق نفسه','تعتمد فائدة تعدد الأحواض على مزيج المنتجات ونظام الورديات. أظهر المعدات المساعدة والتغذية والتفريغ واحتياج المشغل في جدول العرض نفسه. لا تستنتج الطاقة من عدد الأحواض وحده.'],
    ['وثّق تجربة العينة','استخدم منتجاً ممثلاً لتقييم مظهر التغطية المقبول والكسر والهدر وزمن الدورة. واذكر في العرض وخطة القبول أن الأداء الفعلي يعتمد على المنتج والوصفة وظروف التركيب.']
  ]},
  'kahve-kavurma-makinesi-secimi': {title:'اختيار محمصة القهوة: الدفعة والملف وتدفق الإنتاج',desc:'قيّم تخطيط الدفعات وثبات ملف التحميص والتبريد وتدفق التشغيل معاً عند الاستثمار في تحميص القهوة.',sections:[
    ['ميّز مصطلح البحث بدقة','قد تشير عبارة «آلة قهوة صناعية» أيضاً إلى معدات تحضير المشروبات. إذا كنت تبحث عن تحميص الحبوب، فحدّد «محمصة قهوة» ونظام الدفعات المطلوب. لا يتناول هذا الدليل اختيار آلات الإسبريسو أو التقديم.'],
    ['اربط هدف الدفعة بالإنتاج اليومي','تكتسب أوقات الإحماء والتحميص والتفريغ والتبريد وتبديل المنتج أهمية تماثل حجم الدفعة. اذكر هدفك على أنه إنتاج الحبوب المحمصة يومياً. ولا تستنتج طاقة الوردية من رقم دفعة واحدة.'],
    ['اسأل عن تكرار ملف التحميص','ينبغي أن يوضح المورد طريقة تسجيل الحرارة والوقت والإعدادات التي يمكن للمشغل تعديلها وكيفية تكرار الوصفة في الدفعة التالية. سجّل نوع الحبوب وظروفها الأولية أثناء التجربة.'],
    ['خطط للتبريد والعملية التالية','تعتمد خطوات التبريد والانتظار والطحن أو التعبئة بعد التحميص على استراتيجية المنتج. ينبغي التفكير في سرعة هذه المحطات ومساحتها مع اختيار المحمصة.'],
    ['تحقق من الملاءمة الفنية','يعرض الكتالوج الإلكتروني لسونوز ماكينة طرازاً لتحميص القهوة بالرمز HT 30 CR، وقد وُحّد رمز المنتج في الموقع مع الكتالوج. اطلب ورقة فنية حديثة وتجربة بحبوب ممثلة للتحقق من التدفئة وخيارات التحكم وملاءمة الموقع.']
  ]},
  'bantli-donerli-kavurma-makinesi-secimi': {title:'محمصة المكسرات بالسير أم الدوارة؟ دليل الاختيار',seoTitle:'محمصة مكسرات بالسير أم دوارة؟',desc:'قارن بين آلات التحميص بالسير والدوارة من خلال تجربة المنتج وتخطيط المصنع والرسم الفني ونطاق العرض.',sections:[
    ['ابدأ بمواءمة نوع الآلة مع المنتج والنتيجة المطلوبة','يعرض كتالوج سونوز ماكينة آلات التحميص بالسير والآلات الدوارة ضمن مجموعتين منفصلتين. لا يكفي اسم الآلة وحده لتحديد ملاءمتها للمنتج أو النتيجة المتوقعة. اذكر نوع المنتج وحالة القشرة واللون والقوام المطلوبين وتكرار تغيير المنتج وخطوات المعالجة التالية في طلب واحد.'],
    ['اجعل تجربة العينة معياراً للاختيار','جهّز عينة ممثلة من المادة الخام ونموذجاً للمنتج النهائي المقبول. اتفق مسبقاً مع الشركة المصنّعة على الإعدادات والنتائج التي ستُسجّل أثناء التجربة. لا تعتبر وصفاً عاماً لم يُختبر على عينتك ضماناً للشراء.'],
    ['قارن مخطط المكان بالرسم الفني الأحدث','تساعد الأبعاد العامة في الكتالوج على التحقق الأولي من المساحة. أكّد مسارات الأبواب والنقل ووصول المشغل ومساحات التنظيف والصيانة ووصلات خط الإنتاج على رسم الطلب الأحدث. لا تفترض أن أبعاد الكتالوج هي الأبعاد النهائية لآلة تُصنع حسب الطلب.'],
    ['اسأل عن التدفئة والمعدات المساعدة معاً','استخدم أنواع التدفئة والقيم الفنية الظاهرة لكل طراز في الكتالوج كمرجع أولي. أدرج التوصيلات الكهربائية أو الوقود والتهوية والتغذية والتبريد والنقل كلّاً على حدة في العرض. أكّد الملاءمة النهائية وفق ظروف الموقع وورقة المواصفات الحديثة.'],
    ['قارن العروض ضمن النطاق نفسه','قارن الآلة والمعدات المشمولة ومسؤوليات التركيب والتسليم والتدريب ومعايير قبول التجربة للخيارين تحت العناوين نفسها. ينبغي أن تستند النتيجة إلى تجربة بمنتجك ورسم فني خاص بالطلب.']
  ]},
  'denizli-kuruyemis-makinesi-imalati': {title:'تصنيع آلات المكسرات في دنيزلي: ما الذي يتضمنه طلب العرض؟',seoTitle:'مصنع آلات المكسرات في دنيزلي',desc:'دليل عملي للشركات التي تبحث عن مصنع آلات تحميص المكسرات في دنيزلي، من تحديد الاحتياج إلى النقاش الفني والعينة والعرض المصنّع حسب الطلب.',sections:[
    ['صف الاحتياج قبل اختيار اسم الآلة','اذكر المنتج المراد معالجته ونتيجة التحميص المطلوبة وخطوات الإنتاج الحالية ومكان الآلة الجديدة في الخط. ينبغي أن يعتمد اختيار نوع الآلة على هذه المعلومات؛ فاسم المنتج وحده لا يثبت الملاءمة.'],
    ['أكّد المعلومات الفنية الحديثة معاً','يعرض كتالوج سونوز ماكينة الإلكتروني عائلات وطرازات مختلفة. أرسل رمز الطراز الذي تهتم به ومخطط الموقع والتوصيلات المتاحة. يجب تأكيد الأبعاد والتكوين وفق الرسم الفني الحديث للآلة المصنّعة حسب الطلب.'],
    ['ناقش العينة ومعايير القبول مبكراً','إن أمكن، أرفق عينة ممثلة من المنتج ونموذجاً للنتيجة التي تتوقعها. وإذا خُطط لإجراء تجربة، فاتفقوا كتابةً على الخصائص التي ستُقيّم وكيفية تسجيل النتيجة. اعتبر ادعاءات الأداء غير المؤكدة بحاجة إلى اختبار.'],
    ['قارن العروض ضمن النطاق نفسه','اطلب تفاصيل منفصلة عن نطاق الآلة والمعدات المساعدة وتوصيلات الموقع ومسؤوليات التسليم والتركيب والتدريب وخطوات القبول. يساعد ذلك على معرفة ما يتضمنه كل عرض ومقارنته بالآخر.'],
    ['استعد للاجتماع في دنيزلي','يقع سونوز ماكينة في موقع تجار المواد الغذائية، 7133 سوكاك رقم 5، حي بوزبورون، مركز أفندي، دنيزلي. للاجتماع الأولي، أرسل نوع المنتج والنتيجة المطلوبة ومعلومات الموقع المتاحة ورمز أي طراز في الكتالوج تفكر فيه.']
  ]},
  'kuruyemis-kavurma-makinesi-teklif-talebi': {title:'عرض سعر آلة تحميص المكسرات: ما المعلومات التي ترسلها؟',seoTitle:'طلب عرض سعر لمحمصة المكسرات',desc:'أعد طلب عرض سعر مفيداً لآلة تحميص المكسرات باستخدام قائمة تشمل المنتج والنتيجة المطلوبة والموقع ونوع الآلة ونطاق الطلب.',sections:[
    ['اشرح المنتج والنتيجة المطلوبة','اذكر اسم المنتج المراد معالجته وطريقة تحضيره الحالية وصفات التحميص التي تتوقعها. قد تختلف متطلبات العملية باختلاف المنتج؛ لذلك اذكر كل منتج على حدة إذا كنت تخطط لمعالجة أكثر من نوع. وإن أمكن، أرسل عينة ممثلة من المادة الخام ونموذجاً للمنتج النهائي المطلوب.'],
    ['لا تعتبر نوع الآلة قراراً نهائياً بمفرده','يمكنك الإشارة إلى أنك تفكر في نظام بالسير أو دوار، لكن قيّم الاختيار النهائي مع تجربة المنتج ومتطلبات العملية وظروف الموقع. اسم الآلة وحده لا يؤكد ملاءمتها للمنتج أو النتيجة.'],
    ['أرسل معلومات الموقع والمخطط','قدّم أبعاد منطقة التركيب والأبواب ومسارات النقل ووصلات المعدات الموجودة وإمكانية الوصول إلى الكهرباء أو الوقود وظروف التهوية. يمكن لمخطط أو صورة للخط الحالي أن يسهّل النقاش الفني الأولي. أكّد الأبعاد النهائية وفق الرسم الفني الخاص بالطلب.'],
    ['اطلب تفصيل نطاق العرض بنداً بنداً','اطلب توضيحاً منفصلاً للآلة والمعدات المساعدة المشمولة ومسؤولية توصيلات الموقع ونطاق التسليم والتركيب والتدريب وخطوات القبول. يساعد ذلك على مقارنة العروض المختلفة ضمن النطاق نفسه.'],
    ['نموذج طلب مختصر جاهز للإرسال','املأ الحقول: «المنتج المراد معالجته: … / النتيجة المطلوبة: … / نوع الآلة أو طراز الكتالوج الذي أفكر فيه: … / تفاصيل الموقع والخط الحالي: … / العينة أو الرسم المتاح: … / البنود المطلوب توضيحها في العرض: …». لا تخمّن التفاصيل الفنية غير المعروفة؛ أكّدها مع الشركة المصنّعة.']
  ]},
  'kuruyemis-kavurma-makinesi-teknik-cizim-kontrolu': {title:'الرسم الفني لمحمصة المكسرات: قائمة تحقق قبل الطلب',seoTitle:'دليل الرسم الفني لمحمصة المكسرات',desc:'دليل عملي للتحقق من الأبعاد ومسارات النقل والوصلات وإمكانية الصيانة في رسم آلة تحميص المكسرات قبل الطلب.',sections:[
    ['ميّز بين أبعاد الكتالوج ورسم الطلب','تفيد أبعاد الكتالوج الإلكتروني في المراجعة الأولية. أكّد كتابةً الأبعاد الخارجية ونقاط التوصيل والخيارات للآلة المصنّعة حسب الطلب وفق الرسم الفني الحديث. لا تعتبر رسماً لطراز سابق أو رسماً من الكتالوج وثيقة الاعتماد النهائية.'],
    ['تحقق من طريقة إدخال الآلة إلى المصنع','راجع مساحة التركيب وكذلك التفريغ من مركبة النقل ومرور الأبواب والممرات ومساحة الدوران والحركة أثناء التركيب. قارن القياسات مع مسؤول الموقع والشركة المصنّعة على الرسم نفسه.'],
    ['حدّد وصلات خط الإنتاج','وضّح على الرسم اتجاه تغذية المنتج وخروجه والمعدات السابقة واللاحقة ومساحة عمل المشغّل ونقاط التقاطع مع الخط الموجود. إذا كان أحد التوصيلات أو اتجاهها غير واضح، فاسأل الفريق الفني قبل اعتماد التصنيع.'],
    ['أكّد ملاحظات الكهرباء والوقود والتهوية','استناداً إلى خيار التسخين المذكور في الكتالوج والرسم، تحقّق مع المختصين من توصيلات الكهرباء أو الوقود والتهوية ومتطلبات المدخنة في الموقع. لا تفترض القيم الفنية الدقيقة قبل تأكيدها من ورقة الآلة الحديثة وتصميم الموقع.'],
    ['وثّق التنظيف والصيانة والقبول','اسأل عن إمكانية الوصول للتنظيف اليومي والصيانة الدورية والأجزاء القابلة للفك وطريقة الخدمة. تأكد من وجود تاريخ مراجعة وموافقة الطرفين على الرسم. وإذا خُطط لتجربة عينة منتج، فأدرج معايير القبول منفصلة في العرض.']
  ]},
  'kuruyemis-kavurma-makinesi-numune-denemesi': {title:'تجربة تحميص المكسرات: العينة ومعايير القبول',seoTitle:'تجربة عينة لآلة تحميص المكسرات',desc:'قيّم عرض الآلة باستخدام منتجك: حضّر عينة ممثلة، وسجّل بيانات التجربة، واتفق كتابةً على معايير القبول قبل الطلب.',sections:[
    ['اختر عينة ممثلة، لا أفضل حبات فقط','ينبغي أن تمثل العينة الدفعة التي ستستخدمها عادةً في الإنتاج. سجّل نوع المنتج وحالة القشرة وأي معالجة مسبقة وتاريخ الدفعة. قد لا توضح بضع حبات كبيرة ومنتقاة سلوك الآلة مع المنتج المعتاد. اتفق مع المورد مسبقاً على كمية العينة وطريقة إرسالها.'],
    ['حوّل عبارة «تحميص جيد» إلى وصف واضح','اشرح اللون والقوام والرائحة التي تريدها، وبيّن بمنتج نموذجي أو صورة العيوب التي لا تقبلها. إذا استُخدم قياس للرطوبة أو اللون، فاتفق على الجهاز ومكان أخذ العينة ووقته ومن سيسجل النتيجة. ويمكن للفحص البصري أن يفيد أيضاً إذا ثُبّتت الإضاءة ومدة التبريد وعينة المقارنة.'],
    ['سجّل التغييرات أثناء التجربة','اطلب من المورد تسجيل الإعدادات التي تغيّرت ووقت كل تغيير. احتفظ بسجل واحد لحالة المنتج الداخل وإعدادات الآلة ومدة العملية وملاحظات المنتج الخارج وأي توقف. وإذا جُرّبت منتجات أو وصفات مختلفة، فدوّن كل واحدة على حدة ولا تدمج نتائجها في متوسط واحد.'],
    ['افحص المنتج بعد التبريد وفي الخطوة التالية','قد يختلف انطباعك عن العينة الساخنة بعد أن تبرد. اتفق على وقت التقييم، وإذا كان المنتج سيُعبأ فحدّد موعد فحصه داخل العبوة. أدرج الكسر أو فاقد الغربلة أو سلوك التعبئة إذا كانت مهمة؛ فتجربة المحمصة وحدها لا تثبت ملاءمة الخط كله.'],
    ['اكتب شروط القبول قبل الطلب','اذكر في العرض مادة الاختبار وصفات المنتج النهائي المستهدفة وطريقة القياس وشروط إعادة التجربة ومسؤولية كل طرف. استبدل عبارات عامة مثل «تم قبول العينة» بالنتيجة الفعلية والظروف التي تحققت فيها. تأكد من توفر تجربة العينة ونطاقها؛ فهذا الدليل لا يفترض أن كل مصنع يقدم الخدمة نفسها.']
  ]},
  'kuruyemis-eleme-makinesi-secimi': {title:'اختيار آلة غربلة المكسرات: ما الذي ينبغي مقارنته؟',seoTitle:'دليل اختيار آلة غربلة المكسرات',desc:'قارن عروض آلات غربلة المكسرات وفق عينة المنتج والكسور المستهدفة وفاقد المنتج السليم واتصالات خط الإنتاج.',sections:[
    ['ابدأ بتحديد ما الذي تريد فصله','التصنيف حسب الحجم، وفصل القطع المكسورة، وإزالة المواد الغريبة أهداف مختلفة. وضّح ما الذي يجب أن يبقى في المنتج وما الذي ينبغي فصله. وإذا كنت تحتاج إلى أكثر من درجة، فسمّ كل جزء خارج على حدة. هكذا يرتبط العرض بالمهمة المطلوبة، لا باسم عام مثل «آلة غربلة».'],
    ['اعرض المنتج والدرجات المستهدفة على المورد','أرسل إن أمكن عينة من دفعة إنتاج عادية ونماذج لكل جزء تريد الحصول عليه. لا تختَر فتحة الغربال اعتماداً على اسم المنتج فقط؛ فالحجم والشكل والهشاشة والتفاوت في الخليط الداخل قد تؤثر في النتيجة. وإذا لم تتوفر تجربة، فاسأل عن البيانات التي سيُبنى عليها الاختيار.'],
    ['سجّل فاقد المنتج السليم أيضاً','النظر إلى المادة المرفوضة وحدها لا يعطي الصورة كاملة. سجّل كمية المنتج المقبول التي خرجت من المسار الخطأ، وكمية الأجزاء غير المرغوبة التي بقيت مع المنتج الأساسي. اتفق مسبقاً على الكميات وطريقة أخذ العينات. من دون ذلك، لا تكفي عبارات عامة مثل «فصل نظيف» لمقارنة العروض.'],
    ['اسأل عن التنظيف وتغيير الإعدادات وتدفق الخط','اسأل كيف تتغير الإعدادات أو الغرابيل عند تبديل المنتج، وما الأسطح التي يمكن الوصول إليها أثناء التنظيف، وكيف تُسجّل التوقفات أو الانسدادات. تختلف هذه التفاصيل بين الطرازات ويجب تأكيدها بالرسم الفني الحالي أو بعرض الآلة. ضع أيضاً في الحسبان طريقة عمل التحميص قبل الغربلة والتعبئة بعدها.'],
    ['اختم العرض بشروط قبول خاصة بالمنتج','أدرج المنتج والدفعة التي جُرّبت والكسور المستهدفة وفاقد المنتج المقبول وطريقة القياس والمعدات المشمولة وتوصيلات الموقع. وإذا كنت ستعالج عدة منتجات، فلا تفترض أن تجربة منتج واحد تثبت ملاءمة الآلة للجميع. راجع خيارات الغربال وسير الفرز من سونوز ماكينة، ثم أكّد ملاءمة الطراز في مناقشة فنية خاصة بالمشروع.']
  ]}
}
};
