// Full editorial translations for all long-form guides. Each section preserves the
// source article's practical cautions and product-specific details.
export const localizedGuides = {
en: {
  'kuruyemis-kavurma-makinesi-secimi': {title:'How to Choose a Nut Roasting Machine: Questions to Ask',desc:'A buying guide to product recipes, verified line output, heat source, cleaning and service conditions when choosing a nut roaster.',sections:[
    ['Describe the production conditions, not just the product','The fact that one machine can process hazelnuts, almonds, peanuts and seeds does not mean one setting will suit them all. Include particle-size distribution, incoming moisture, shell condition and target colour in the enquiry. Where possible, request a trial using a representative raw-material sample. This lets you discuss the result achieved with your product instead of relying on a general catalogue capacity.'],
    ['Convert nominal capacity into usable output','Ask which product, starting moisture and target result support the machine’s hourly-output claim. Then ask how many kilograms of conforming product will be ready at the end of a shift after changeovers, warm-up, stops, cleaning and cooling. If packaging is slower, a larger roaster alone will not increase total plant output.'],
    ['Compare these items in every quotation','List the heat source and required utilities, feeding method, controls and recipe storage, cooling, dust and shell handling, maintenance access, spare parts, installation and operator training as separate items. Quotes from different suppliers are comparable only when they cover the same scope.'],
    ['Set acceptance criteria before ordering','Agree on the test raw material, finished-product definition, measurement method, trial duration and acceptance owners in the quotation. Choose indicators such as colour, moisture, breakage and rejects to suit the product. If the measurement method is not written down, the parties may interpret the result differently later.'],
    ['How should you assess Sonsuz Makina models?','HT 15, HT 30, HT 75, HT 150, HT 500, HT 750 and HT 1000 are listed in the same model family; do not treat a model number by itself as a verified hourly-capacity guarantee. Request a current technical sheet and an assessment using your own raw material.']
  ]},
  'kavurma-ve-kurutma-arasindaki-fark': {title:'Roasting and Drying: Two Different Production Goals',desc:'Compare the distinct process goals of drying and roasting, including moisture, colour, flavour, energy and finished-product control.',sections:[
    ['Separate the purpose of each process','Drying focuses on controlling moisture; roasting develops flavour, aroma and colour. Even when one machine can perform both tasks, define the incoming conditions and desired output separately. A hotter process does not automatically produce a better roast.'],
    ['Set measurement points in advance','Record when inlet and outlet samples will be taken, how moisture will be measured and how colour will be assessed. Comparisons based only on an operator’s visual judgement are difficult to reproduce across shifts and batches.'],
    ['Include cooling in the line design','The product’s journey does not end when heat treatment is complete. Cooling and holding time can affect how the product behaves during packaging. Plan the roaster’s target output together with cooling and packaging speeds.'],
    ['Run trials with your own raw material','A result obtained with another producer’s product cannot be transferred directly to your incoming moisture and particle size. Before accepting an offer, compare several settings with representative samples and retain the approved result with a written recipe and measurement notes.'],
    ['Match the machine to the process goal','When reviewing HT-series roasting and drying models, state the product and the result you want to achieve. Confirm current technical limits and energy requirements with the manufacturer.']
  ]},
  'kuruyemis-uretim-hatti-planlama': {title:'How to Plan a Nut Processing Line',desc:'Plan feeding, roasting, cooling, screening, seasoning and packaging around real production bottlenecks.',sections:[
    ['Map the product flow first','Show receiving, storage, pre-screening, roasting or drying, cooling, sorting, seasoning and packaging in a single flow diagram. Note the input and output form at each stage. This is a more useful starting point than looking at each machine’s capacity in isolation.'],
    ['Calculate the bottleneck by shift','The slowest required operation determines line output. Matching roaster capacity to packaging speed is not enough: include changeovers, cleaning and planned downtime. Express the target as conforming product packaged during one shift.'],
    ['Design the layout around more than machine dimensions','Allow room for operator routes, service doors, cleaning, product and packaging movement, and waste removal. Check existing electrical and fuel infrastructure, ventilation and possible future expansion on the layout drawing.'],
    ['Break the quotation into scope items','Ask suppliers to list machinery, feeding and transfer equipment, cooling, automation, installation, training and commissioning separately. A component omitted from the initial offer can make an apparently cheaper proposal more expensive overall.'],
    ['Prepare three production scenarios','Create separate scenarios for today’s products and shifts, expected growth and different product recipes. Mark the slowest station in each scenario and identify the conditions under which the investment will actually increase capacity.']
  ]},
  'kuruyemis-kavurma-makinesi-fiyati': {title:'Nut Roaster Prices: How to Compare Quotations',desc:'Clarify scope, capacity, energy, automation and commissioning before comparing nut-roaster quotations.',sections:[
    ['Why can a single price be misleading?','Two roasters sold under the same name may differ in feeding, heating, controls, cooling and service scope. An online price is therefore not the cost of a line installed at your plant. Start by documenting the products, target output, site layout and available utilities together.'],
    ['Divide the offer into four parts','Review the machine itself; auxiliary equipment and connections; installation and commissioning; and operating and maintenance costs. Make exclusions visible, including transport, operator training, an initial spare-parts kit and warranty conditions. Compare total cost of ownership, not just the purchase price.'],
    ['Question the stated capacity','The required figure should describe acceptable finished product, not only the machine’s theoretical throughput. Ask which raw material and recipe were used to measure catalogue capacity. Request a separate shift-output estimate that includes changeovers and cleaning.'],
    ['Choose energy and automation deliberately','The heat source depends on site infrastructure and the planned production schedule. Assess automation through recipe repeatability, operator workload and record-keeping needs rather than simply counting features. Show the capital and operating impact of each option as separate quotation lines.'],
    ['Request comparable proposals','Give every supplier the same product list, sample properties, shift target, installation space and acceptance criteria. Mark included and excluded work in each offer. This prevents an option that omits cooling or commissioning from appearing better value by mistake.']
  ]},
  'kuruyemis-kavurma-makinesi-kapasite-secimi': {title:'How to Choose the Capacity of a Nut Roasting Machine',desc:'Translate an hourly target into shift output and assess recipes, downtime, cooling and packaging bottlenecks together.',sections:[
    ['State the target as finished product','Instead of asking for a “500 kg per hour machine”, specify the amount of conforming product ready for packaging at the end of a shift. Incoming raw-material weight may differ from usable output. Include available operating time and product-change frequency in the calculation.'],
    ['Build a simple capacity model','A starting point for required average line speed is target net output divided by available production time. Then add allowances for quality losses, rework and required stops using your own operating data. This is a quotation-planning framework, not a substitute for the machine’s nominal catalogue capacity.'],
    ['Find the slowest station in the line','Request sustainable output for feeding, roasting, cooling, screening, seasoning and packaging using the same product. A faster roaster cannot by itself fix a slow packaging station. If buffer storage is needed, consider its effect on product quality and traceability.'],
    ['Account for the product mix','One figure for hazelnuts, almonds and seeds may look convenient, but different recipes change the calculation. Create separate scenarios for each main product, estimated batch count and cleaning interval. Assess the busiest day separately from the average day.'],
    ['Close the model choice with a trial','Do not read the model name as a capacity guarantee when comparing HT-series machines. Request a current technical sheet, sample trial and written offer based on site conditions. Acceptance measurements should use the defined product and recipe.']
  ]},
  'kuruyemis-uretim-hatti-kurulum-maliyeti': {title:'How to Estimate the Cost of Setting Up a Nut Processing Line',desc:'A capital-planning guide that includes feeding, cooling, packaging, layout, utilities and commissioning beyond the machine price.',sections:[
    ['Define the product and how it will be sold','Will the line process one product or several nuts? Will the finished product be sold in bulk or retail packs? These choices change the process flow and equipment list. Without them, there is no single reliable figure for “plant cost”.'],
    ['Build the equipment list around the process','Separate required and optional items for raw-material receiving and feeding, pre-screening, heat treatment, cooling, sorting, seasoning, weighing and packaging. State the target net output for each station. Identify transfer and connection equipment missing from a supplier’s offer.'],
    ['Budget for site work separately','Electrical panels and distribution, fuel infrastructure, ventilation, space changes, workplace safety and cleaning requirements should be planned separately from the machine price. Do not combine an installation in an existing plant and a new-building project in the same budget assumption.'],
    ['Include commissioning and operation','List transport, installation, initial recipe trials, operator training, a maintenance plan and starting spare-parts needs. Use your actual shift schedule to estimate energy and labour costs. Do not base the investment decision solely on the purchase price.'],
    ['Prepare a three-scenario budget','Create scopes for a basic line, a line ready for growth and a flexible line for different products. Show expected net output, required floor area and missing components for each. If investment is staged, this reveals which equipment can be deferred.']
  ]},
  'leblebi-uretim-hatti-makineleri': {title:'Roasted Chickpea Production Line: Equipment and Process Sequence',desc:'Assess chickpea preparation, heating, moistening, roasting, screening and packaging as one integrated line.',sections:[
    ['Classify the incoming raw material','Chickpea size, moisture and batch consistency affect settings downstream. Do not expect one machine recipe to suit every batch without recording the raw-material properties. Identify any pre-screening and separation needs at the intake stage.'],
    ['Place preparation operations in the flow','The target product determines whether steps such as heating, moistening and dipping are needed. Although these stations may look like separate purchase items, line speed and transfer method should be designed together. Relevant equipment appears on separate product pages in the Sonsuz Makina catalogue.'],
    ['Specify roasting and resting conditions','Target colour and texture are key process outputs. Conditions should be validated for the chickpea batch and intended product. During a trial, keep the inlet and outlet samples, processing time and operator notes together in one record.'],
    ['Measure screening and packaging bottlenecks','Even with high roaster output, slower screening, sorting or filling reduces usable shift output. Measure conforming product separately at each station. Include rejects and rework flow in the layout plan.'],
    ['Request a process diagram with the quotation','The written offer should state which machines are included, how product transfers between stations, and the space and energy requirements. Do not infer a complete line from machine names alone; confirm scope with a drawing and acceptance plan.']
  ]},
  'kuruyemis-paketleme-makinesi-gramaj-secimi': {title:'Nut Packaging Machines: Choosing Pack Weight and Weighing Heads',desc:'Compare semi-automatic and automatic filling options by pack weight, product fragility, target count and line flow.',sections:[
    ['Do not treat the weight range as one number','Record the smallest and largest pack sizes as well as the weights that account for most sales. If the line will pack different nuts or mixes, assess each product’s flow and breakage behaviour separately. This avoids choosing a machine only because it can handle the extreme sizes.'],
    ['Connect packs per minute to the shift plan','Use the daily sales plan to estimate pack count and shift time. Reduce available production time for film changes, product changes, weight checks and cleaning. Keep theoretical packs per minute separate from the accepted net pack count.'],
    ['Interpret the number of weighing heads correctly','Two-, four- or five-head designs may suit different weighing and feeding needs; more heads do not automatically produce a better result in every application. Test accuracy, product fragility, target weight and feeding arrangement together.'],
    ['Include work around the filler','Mark feeding, pack format, sealing, date coding, check-weighing and case preparation in the quotation scope. The phrase “packaging machine” does not mean all of this equipment is included.'],
    ['Set up acceptance tests with samples','Include the most frequently packed products and weights in the test list. Record target-weight accuracy, breakage, faulty packs, product-change time and operator intervention. Verify final performance with the actual product and packaging.']
  ]},
  'elektrikli-dogalgazli-kavurma-makinesi-secimi': {title:'Electric or Gas Roasting? Choosing a Heat Source',desc:'Choose between electric and gas roasting by considering site utilities, operating profile, process control and total running cost.',sections:[
    ['Check the available site infrastructure first','Record the electrical connection and load capacity, gas access, ventilation and installation constraints. Choosing only by energy-unit price can overlook connection, permitting and site-installation work.'],
    ['Keep the comparison conditions consistent','Assess both options using the same raw material, incoming moisture, target finished product and net shift output. Comparing one system’s rated power with the other’s measured consumption will not give a sound result. Ask the supplier for the test conditions and measurement method.'],
    ['Allow for part-load use and changeovers','The machine may not run at full capacity continuously. Ask how warm-up, standby, recipe changes and stops affect the energy calculation. Your assumed usage profile should reflect the actual shift schedule.'],
    ['Put investment and operating costs in one table','Show machine and utility investment, energy, maintenance, spare parts and potential downtime on separate lines. Date and state the units for energy-price assumptions so the calculation can be updated when prices change.'],
    ['Complete the decision using site-specific conditions','Request a current technical quotation using the product, capacity target and existing site details. Confirm separately with the manufacturer whether each heating option suits the selected Sonsuz Makina model and configuration.']
  ]},
  'draje-kaplama-makinesi-secimi': {title:'Choosing a Coating Machine: Pan, Product and Batch Plan',desc:'Define the product core, coating goal, pan type, cleaning and batch flow before investing in a coating machine.',sections:[
    ['Identify the product to be coated','Almonds, hazelnuts and other centres can differ in size, surface behaviour and fragility. Do not group sugar, chocolate and other coating goals under one generic recipe. State the product and desired finish clearly in the enquiry.'],
    ['Read batch volume together with cycle time','Pan volume alone does not tell you daily output. Define a full cycle that includes loading, coating, intermediate drying or holding, unloading and cleaning. Plan the shift target using the number of cycles that can actually be completed.'],
    ['Ask about materials and cleaning access','Technical evaluation should cover product-contact surfaces, cleaning method, changeover time between products and maintenance access. Where different coatings are used, cross-contamination controls belong in the operating plan.'],
    ['Compare single and double pans on equal scope','The benefits of multiple pans depend on the product mix and shift pattern. Show auxiliary equipment, feeding, discharge and operator requirements in the same quotation table. Do not infer capacity from pan count alone.'],
    ['Document the sample trial','Use a representative product to assess acceptable coating appearance, breakage, rejects and cycle time. State in the offer and acceptance plan that actual performance depends on product, recipe and installation conditions.']
  ]},
  'kahve-kavurma-makinesi-secimi': {title:'Choosing a Coffee Roaster: Batch, Profile and Production Flow',desc:'Assess batch planning, profile repeatability, cooling and operating flow together when investing in coffee roasting.',sections:[
    ['Distinguish the search term correctly','“Industrial coffee machine” can also refer to beverage-preparation equipment. For a bean-roasting investment, specify “coffee roaster” and the intended batch pattern. This guide does not cover espresso or serving machines.'],
    ['Connect batch targets to daily output','Warm-up, roasting, discharge, cooling and product changes matter as much as batch size. State the target as daily roasted-bean output. Do not derive shift capacity from a single batch figure.'],
    ['Ask how profiles are repeated','The supplier should demonstrate how temperature and time are recorded, which settings the operator can adjust and how a recipe is repeated on the next batch. During trials, record bean type and starting conditions.'],
    ['Plan cooling and the next operation','After roasting, cooling, holding, grinding or packaging depends on the product strategy. Consider the speed and space requirements of these stations alongside the roaster choice.'],
    ['Verify technical suitability','The Sonsuz Makina catalogue lists an HT 30 coffee-roasting model. Request a current technical sheet and a trial with representative beans to confirm capacity, heat source, control options and site suitability.']
  ]}
},
ar: {
  'kuruyemis-kavurma-makinesi-secimi': {title:'كيفية اختيار آلة تحميص المكسرات: أسئلة ينبغي طرحها',desc:'دليل شراء يشرح وصفات المنتج والإنتاج الفعلي ومصدر الحرارة والتنظيف والخدمة عند اختيار محمصة المكسرات.',sections:[
    ['صف ظروف الإنتاج لا اسم المنتج فقط','إمكانية استخدام الآلة نفسها للبندق واللوز والفول السوداني والبذور لا تعني أن إعداداً واحداً يناسبها جميعاً. أدرج توزيع أحجام الحبات ورطوبة المادة الخام وحالة القشرة واللون المستهدف في طلب العرض. واطلب، إن أمكن، تجربة عينة ممثلة من خامتك. عندها تناقش النتيجة على منتجك بدلاً من الاكتفاء بطاقة عامة في الكتالوج.'],
    ['حوّل الطاقة الاسمية إلى إنتاج فعلي صالح','اسأل عن المنتج ورطوبته الأولية والنتيجة التي بُني عليها ادعاء الإنتاج بالساعة. ثم اسأل عن كمية المنتج المطابق للمواصفات التي ستبقى في نهاية الوردية بعد تبديل المنتجات والإحماء والتوقف والتنظيف والتبريد. إذا كانت التعبئة أبطأ، فلن ترفع المحمصة الأكبر وحدها إنتاج المصنع الكلي.'],
    ['قارن البنود نفسها في كل عرض','اطلب إدراج مصدر الحرارة والمرافق المطلوبة وطريقة التغذية والتحكم وحفظ الوصفات والتبريد ومعالجة الغبار والقشور وإمكانية الصيانة وقطع الغيار والتركيب وتدريب المشغل كبنود منفصلة. لا تكون عروض الموردين قابلة للمقارنة إلا إذا شملت النطاق نفسه.'],
    ['حدد معايير القبول قبل الطلب','اتفق في العرض على خامة الاختبار وتعريف المنتج النهائي وطريقة القياس ومدة التجربة والمسؤولين عن القبول. اختر مؤشرات مثل اللون والرطوبة والكسر والهدر بحسب المنتج. إذا لم تُكتب طريقة القياس فقد يفسر الطرفان النتيجة لاحقاً بطريقتين مختلفتين.'],
    ['كيف تقيّم طرازات سونوز ماكينة؟','تُدرج الطرازات HT 15 وHT 30 وHT 75 وHT 150 وHT 500 وHT 750 وHT 1000 ضمن عائلة واحدة؛ لا تعتبر رقم الطراز وحده ضماناً لإنتاج مؤكد بالساعة. اطلب ورقة فنية حديثة وتقييماً باستخدام خامتك.']
  ]},
  'kavurma-ve-kurutma-arasindaki-fark': {title:'التحميص والتجفيف: هدفان مختلفان للإنتاج',desc:'قارن بين هدفي التجفيف والتحميص من حيث الرطوبة واللون والنكهة والطاقة وضبط المنتج النهائي.',sections:[
    ['ميّز هدف كل عملية','يركز التجفيف على التحكم في الرطوبة، بينما يهدف التحميص إلى تطوير النكهة والرائحة واللون. حتى إذا أمكن للآلة نفسها تنفيذ المهمتين، ينبغي تعريف ظروف الدخول والخصائص المطلوبة عند الخروج لكل منهما. فالمعالجة بدرجة حرارة أعلى لا تعني تلقائياً تحميصاً أفضل.'],
    ['حدد نقاط القياس مسبقاً','سجّل وقت أخذ عينات الدخول والخروج وطريقة قياس الرطوبة وكيفية تقييم اللون. يصعب تكرار المقارنة بين الورديات والدفعات إذا اعتمدت على الملاحظة البصرية للمشغل وحدها.'],
    ['لا تنس التبريد في تصميم الخط','لا تنتهي رحلة المنتج على الخط بانتهاء المعالجة الحرارية. فقد يؤثر التبريد ووقت الانتظار في سلوك المنتج أثناء التعبئة. خطط لإنتاج المحمصة المستهدف مع سرعة التبريد والتعبئة معاً.'],
    ['أجر التجارب على خامتك','لا يمكن نقل نتيجة منتج مورد آخر مباشرة إلى رطوبة خامتك وحجم حباتها. قارن عدة إعدادات بعينات ممثلة قبل قبول العرض، واحتفظ بالنتيجة المعتمدة مع وصفة مكتوبة وملاحظات القياس.'],
    ['طابق الآلة مع هدف المعالجة','عند مراجعة طرازات التحميص والتجفيف من سلسلة HT، اذكر المنتج والنتيجة التي تريدها. أكّد الحدود الفنية الحالية ومتطلبات الطاقة مع الشركة المصنعة.']
  ]},
  'kuruyemis-uretim-hatti-planlama': {title:'كيفية تخطيط خط لمعالجة المكسرات',desc:'خطط للتغذية والتحميص والتبريد والغربلة والتتبيل والتعبئة على أساس اختناقات الإنتاج الفعلية.',sections:[
    ['ارسم تدفق المنتج أولاً','اعرض الاستلام والتخزين والغربلة الأولية والتحميص أو التجفيف والتبريد والفرز والتتبيل والتعبئة في مخطط واحد. سجّل شكل المنتج عند دخول كل مرحلة وخروجه منها. هذه بداية أنفع من النظر إلى طاقة كل آلة منفردة.'],
    ['احسب عنق الزجاجة لكل وردية','تحدد أبطأ عملية ضرورية إنتاج الخط. ولا يكفي جعل طاقة التحميص مساوية لسرعة التعبئة؛ أدرج تبديل المنتجات والتنظيف والتوقف المخطط. عبّر عن الهدف بكمية المنتج المطابق للمواصفات والمعبأ خلال الوردية.'],
    ['خطط للموقع بما يتجاوز أبعاد الآلة','خصص مساحة لمسار المشغل وفتحات الصيانة والتنظيف وحركة المنتج والعبوات وإخراج النفايات. افحص على الرسم البنية الكهربائية والوقود والتهوية وإمكانية التوسع مستقبلاً.'],
    ['قسّم نطاق العرض إلى بنود','اطلب إدراج الآلات ومعدات التغذية والنقل والتبريد والأتمتة والتركيب والتدريب والتشغيل الأولي بصورة منفصلة. فقد يجعل عنصر محذوف العرض الأرخص ظاهرياً أعلى تكلفة عند اكتمال المشروع.'],
    ['أعد ثلاثة سيناريوهات للإنتاج','أنشئ سيناريو للإنتاج والورديات الحالية، وآخر للنمو المتوقع، وثالث لوصفات منتجات مختلفة. حدّد أبطأ محطة في كل سيناريو واعرف الظروف التي سيزيد الاستثمار عندها الطاقة فعلاً.']
  ]},
  'kuruyemis-kavurma-makinesi-fiyati': {title:'أسعار محمصات المكسرات: كيف تقارن عروض الأسعار؟',desc:'حدّد النطاق والطاقة والوقود والأتمتة والتشغيل الأولي قبل مقارنة عروض محمصات المكسرات.',sections:[
    ['لماذا قد يكون السعر الواحد مضللاً؟','قد تختلف آلتان تحملان الاسم نفسه في التغذية والتسخين والتحكم والتبريد والخدمات المشمولة. لذلك لا يمثل سعر الإنترنت تكلفة خط مركب في مصنعك. ابدأ بتوثيق المنتجات والإنتاج المستهدف ومخطط الموقع والمرافق المتاحة في ملف واحد.'],
    ['قسّم العرض إلى أربعة أجزاء','راجع الآلة نفسها، والمعدات المساعدة والتوصيلات، والتركيب والتشغيل الأولي، ومصاريف التشغيل والصيانة. أظهر بوضوح ما لا يشمله العرض مثل النقل وتدريب المشغل ومجموعة قطع الغيار الأولية وشروط الضمان. قارن التكلفة الكلية للامتلاك لا سعر الشراء وحده.'],
    ['استوضح معنى الطاقة المذكورة','ينبغي أن يصف الرقم المطلوب المنتج النهائي المقبول، لا التدفق النظري للآلة فقط. اسأل عن الخامة والوصفة المستخدمتين لقياس طاقة الكتالوج. واطلب حساباً منفصلاً لإنتاج الوردية يشمل تبديل المنتجات والتنظيف.'],
    ['اختر الوقود والأتمتة عن قصد','يعتمد مصدر الحرارة على مرافق الموقع وجدول الإنتاج المخطط. قيّم الأتمتة من خلال تكرار الوصفة وعبء المشغل والحاجة إلى تسجيل البيانات، لا بعدد الخصائص وحده. أظهر أثر كل خيار في الاستثمار والتشغيل كبند مستقل.'],
    ['اطلب عروضاً قابلة للمقارنة','أرسل إلى كل مورد قائمة المنتجات وخصائص العينات وهدف الوردية ومساحة التركيب ومعايير القبول نفسها. وعلّم الأعمال المشمولة والمستثناة في كل عرض. يمنع ذلك اعتبار خيار ناقص التبريد أو التشغيل الأولي أفضل قيمة بالخطأ.']
  ]},
  'kuruyemis-kavurma-makinesi-kapasite-secimi': {title:'كيفية اختيار طاقة محمصة المكسرات',desc:'حوّل الهدف بالساعة إلى إنتاج الوردية وقيّم الوصفات والتوقف والتبريد واختناق التعبئة معاً.',sections:[
    ['اكتب الهدف على هيئة منتج نهائي','بدلاً من طلب «آلة بطاقة 500 كغ في الساعة»، حدّد كمية المنتج المطابق للمواصفات والجاهز للتعبئة عند نهاية الوردية. قد يختلف وزن الخام الداخل عن الناتج الصالح. وأدرج وقت التشغيل المتاح وتكرار تبديل المنتج في الحساب.'],
    ['أنشئ نموذجاً بسيطاً للطاقة','يمكن البدء بحساب متوسط سرعة الخط المطلوبة عبر قسمة صافي الإنتاج المستهدف على وقت الإنتاج المتاح. ثم أضف مخصصات فقد الجودة وإعادة المعالجة والتوقف الضروري استناداً إلى بيانات تشغيل منشأتك. هذا إطار لإعداد العرض وليس بديلاً عن الطاقة الاسمية للآلة في الكتالوج.'],
    ['اعثر على أبطأ محطة في الخط','اطلب إنتاجاً مستداماً للتغذية والتحميص والتبريد والغربلة والتتبيل والتعبئة باستخدام المنتج نفسه. لن تعالج المحمصة الأسرع وحدها بطء محطة التعبئة. وإذا لزم مخزون وسيط ففكّر في أثره على الجودة وإمكانية التتبع.'],
    ['احتسب تنوع المنتجات','قد يبدو استخدام رقم واحد للبندق واللوز والبذور سهلاً، لكن اختلاف الوصفات يغيّر الحساب. أنشئ سيناريو لكل منتج أساسي مع عدد الدفعات المتوقع وفاصل التنظيف. وقيّم أكثر الأيام ازدحاماً منفصلة عن متوسط الأيام.'],
    ['احسم اختيار الطراز بالتجربة','لا تقرأ اسم طراز سلسلة HT على أنه ضمان للطاقة. اطلب ورقة فنية حديثة وتجربة عينة وعرضاً مكتوباً يستند إلى ظروف الموقع. ينبغي إجراء قياس القبول على المنتج والوصفة المحددين.']
  ]},
  'kuruyemis-uretim-hatti-kurulum-maliyeti': {title:'كيفية تقدير تكلفة إنشاء خط لمعالجة المكسرات',desc:'دليل استثماري يشمل التغذية والتبريد والتعبئة والموقع والمرافق والتشغيل الأولي إلى جانب سعر الآلة.',sections:[
    ['حدد المنتج وطريقة بيعه','هل سيعالج الخط نوعاً واحداً أم أنواعاً متعددة من المكسرات؟ وهل سيباع المنتج النهائي سائبا أم في عبوات تجزئة؟ يغيّر هذان القراران تدفق الخط وقائمة المعدات. ولا يمكن تحديد رقم موثوق واحد لتكلفة المصنع من دونهما.'],
    ['استخرج قائمة المعدات من تدفق العملية','افصل البنود الضرورية والاختيارية للاستلام والتغذية والغربلة الأولية والمعالجة الحرارية والتبريد والفرز والتتبيل والوزن والتعبئة. اكتب صافي الإنتاج المستهدف لكل محطة. وأظهر معدات النقل والتوصيل غير المدرجة في عرض المورد.'],
    ['ضع ميزانية مستقلة لأعمال الموقع','خطط للوحات والتوزيع الكهربائي وبنية الوقود والتهوية وتعديلات المساحة والسلامة المهنية ومتطلبات التنظيف بصورة منفصلة عن سعر الآلات. ولا تخلط تركيباً في مصنع قائم بمشروع مبنى جديد ضمن افتراض الميزانية نفسه.'],
    ['أدرج التشغيل الأولي والتشغيل اليومي','سجّل النقل والتركيب وتجارب الوصفة الأولية وتدريب المشغل وخطة الصيانة وقطع الغيار الأولية. استخدم جدول الورديات الفعلي لديك لتقدير الطاقة والعمالة. لا تتخذ قرار الاستثمار اعتماداً على سعر الشراء وحده.'],
    ['أعد ميزانية بثلاثة سيناريوهات','أنشئ نطاقاً لخط أساسي وآخر جاهز للنمو وثالثاً مرناً لمنتجات متنوعة. أظهر الإنتاج الصافي المتوقع والمساحة المطلوبة والمكونات الناقصة لكل منها. وإذا كان الاستثمار مرحلياً فسيتضح أي المعدات يمكن تأجيلها.']
  ]},
  'leblebi-uretim-hatti-makineleri': {title:'خط إنتاج الحمص المحمص: المعدات وتسلسل العمليات',desc:'قيّم إعداد الحمص والتسخين والترطيب والتحميص والغربلة والتعبئة كخط متكامل.',sections:[
    ['صنّف المادة الخام الواردة','يؤثر حجم حبات الحمص ورطوبتها وثبات الدفعات في إعدادات المراحل التالية. لا تتوقع أن تناسب وصفة آلة واحدة كل الدفعات من دون تسجيل خصائص الخام. حدّد الحاجة إلى الغربلة والفصل الأولي عند الاستلام.'],
    ['أدرج عمليات الإعداد في تدفق الخط','يحدد المنتج المستهدف الحاجة إلى خطوات مثل التسخين والترطيب والتغميس. قد تبدو هذه المحطات بنود شراء مستقلة، لكن ينبغي تصميم سرعة الخط وطريقة النقل بينها معاً. وتظهر المعدات ذات الصلة في صفحات منتجات منفصلة بكتالوج سونوز ماكينة.'],
    ['صف ظروف التحميص والراحة','اللون والقوام المستهدفان من أهم نواتج العملية. يجب التحقق من ظروف التشغيل بحسب دفعة الحمص والمنتج المطلوب. أثناء التجربة، احتفظ بعينتي الدخول والخروج ومدة المعالجة وملاحظات المشغل في سجل واحد.'],
    ['قِس اختناق الغربلة والتعبئة','حتى مع ارتفاع خرج المحمصة، يقل صافي إنتاج الوردية إذا كانت الغربلة أو الفرز أو التعبئة أبطأ. قِس كمية المنتج المطابق في كل محطة على حدة. وأدرج تدفق الهدر وإعادة المعالجة في مخطط الموقع.'],
    ['اطلب مخططاً للعملية مع العرض','يجب أن يوضح العرض المكتوب الآلات المشمولة وطريقة نقل المنتج بين المحطات والمساحة والطاقة المطلوبتين. لا تستنتج وجود خط كامل من أسماء الآلات؛ أكّد النطاق برسم وخطة قبول.']
  ]},
  'kuruyemis-paketleme-makinesi-gramaj-secimi': {title:'آلات تعبئة المكسرات: اختيار وزن العبوة ورؤوس الوزن',desc:'قارن خيارات التعبئة شبه الآلية والآلية وفق وزن العبوة وهشاشة المنتج والعدد المستهدف وتدفق الخط.',sections:[
    ['لا تختزل مجال الأوزان في رقم واحد','سجّل أصغر وأكبر وزن للعبوة، إلى جانب الأوزان الأكثر مبيعاً. وإذا كان الخط سيعبئ أنواعاً أو خلطات مختلفة من المكسرات، فقيّم تدفق كل منتج وسلوكه عند الكسر على حدة. يمنع ذلك اختيار آلة لأنها تتعامل مع الأطراف فقط.'],
    ['اربط العبوات في الدقيقة بخطة الوردية','استخدم خطة المبيعات اليومية لتقدير عدد العبوات ومدة الوردية. اطرح من وقت الإنتاج تبديل الرقائق والمنتج وفحص الوزن والتنظيف. وافصل بين عدد العبوات النظري في الدقيقة والعدد الصافي المقبول.'],
    ['افهم عدد رؤوس الوزن بصورة صحيحة','قد تلائم التصاميم ذات الرأسين أو الأربعة أو الخمسة احتياجات مختلفة للوزن والتغذية؛ فزيادة الرؤوس لا تحسن النتيجة تلقائياً في كل تطبيق. اختبر الدقة وهشاشة المنتج والوزن المستهدف وترتيب التغذية معاً.'],
    ['لا تنس الأعمال المحيطة بآلة التعبئة','أدرج في نطاق العرض التغذية وشكل العبوة والإغلاق وطباعة التاريخ وفحص الوزن وتجهيز الكراتين. فمصطلح «آلة تعبئة» لا يعني أن كل هذه المعدات مشمولة.'],
    ['أنشئ اختبار قبول باستخدام عينات','أدرج المنتجات والأوزان الأكثر تعبئة في قائمة الاختبار. وسجّل دقة الوزن والكسر والعبوات المعيبة ووقت تبديل المنتج وتدخل المشغل. تحقّق من الأداء النهائي باستخدام المنتج والعبوة الفعليين.']
  ]},
  'elektrikli-dogalgazli-kavurma-makinesi-secimi': {title:'التحميص بالكهرباء أم بالغاز؟ اختيار مصدر الحرارة',desc:'اختر بين الكهرباء والغاز بمراعاة مرافق الموقع ونمط التشغيل والتحكم بالعملية والتكلفة الكلية.',sections:[
    ['تحقق أولاً من مرافق الموقع المتاحة','سجّل التوصيل الكهربائي وسعة الأحمال وتوفر الغاز والتهوية وقيود التركيب. فالاختيار وفق سعر وحدة الطاقة وحده قد يغفل التوصيلات والتصاريح وأعمال البنية التحتية.'],
    ['ثبّت شروط المقارنة','قيّم الخيارين باستخدام الخام نفسه ورطوبته الأولية والمنتج النهائي المستهدف وصافي إنتاج الوردية. لا تعطي مقارنة القدرة الاسمية لأحد النظامين بالاستهلاك المقاس للآخر نتيجة سليمة. اطلب من المورد شروط الاختبار وطريقة القياس.'],
    ['احتسب التشغيل الجزئي وتبديل المنتجات','قد لا تعمل الآلة باستمرار عند كامل طاقتها. اسأل عن أثر الإحماء والاستعداد وتبديل الوصفات والتوقف على حساب الطاقة. ينبغي أن يشبه نمط الاستخدام المفترض جدول الورديات الفعلي.'],
    ['اجمع الاستثمار والتشغيل في جدول واحد','أدرج استثمار الآلة والمرافق والطاقة والصيانة وقطع الغيار والتوقف المحتمل في بنود مستقلة. اذكر تاريخ وافتراضات أسعار الطاقة ووحداتها كي يمكن تحديث الحساب عند تغير الأسعار.'],
    ['أكمل القرار وفق ظروف الموقع','اطلب عرضاً فنياً حديثاً باستخدام المنتج والطاقة المستهدفة وبيانات الموقع القائم. وأكّد مع الشركة المصنعة بصورة منفصلة ملاءمة كل خيار تسخين للطراز والتكوين المختارين من سونوز ماكينة.']
  ]},
  'draje-kaplama-makinesi-secimi': {title:'اختيار آلة تغطية الدراجيه: الحوض والمنتج وخطة الدفعات',desc:'حدّد قلب المنتج وهدف التغطية ونوع الحوض والتنظيف وتدفق الدفعات قبل الاستثمار في آلة التغطية.',sections:[
    ['حدد المنتج المراد تغطيته','قد تختلف حبات اللوز والبندق وغيرها في الحجم وسلوك السطح والهشاشة. لا تجمع أهداف التغطية بالسكر أو الشوكولاتة أو غيرهما في وصفة عامة واحدة. اذكر المنتج والطبقة النهائية المطلوبة بوضوح في الطلب.'],
    ['قيّم حجم الدفعة مع زمن الدورة','لا يكشف حجم الحوض وحده الإنتاج اليومي. عرّف دورة كاملة تشمل التحميل والتغطية والتجفيف أو الانتظار الوسيط والتفريغ والتنظيف. وخطط لهدف الوردية على أساس عدد الدورات الممكن إنجازها فعلياً.'],
    ['اسأل عن المواد وسهولة التنظيف','ينبغي أن يشمل التقييم الفني أسطح ملامسة المنتج وطريقة التنظيف ووقت الانتقال بين المنتجات وإمكانية الصيانة. وعند استخدام طبقات مختلفة، ينبغي أن تكون مكافحة انتقال التلوث جزءاً من خطة التشغيل.'],
    ['قارن الحوض المفرد والمزدوج بالنطاق نفسه','تعتمد فائدة تعدد الأحواض على مزيج المنتجات ونظام الورديات. أظهر المعدات المساعدة والتغذية والتفريغ واحتياج المشغل في جدول العرض نفسه. لا تستنتج الطاقة من عدد الأحواض وحده.'],
    ['وثّق تجربة العينة','استخدم منتجاً ممثلاً لتقييم مظهر التغطية المقبول والكسر والهدر وزمن الدورة. واذكر في العرض وخطة القبول أن الأداء الفعلي يعتمد على المنتج والوصفة وظروف التركيب.']
  ]},
  'kahve-kavurma-makinesi-secimi': {title:'اختيار محمصة القهوة: الدفعة والملف وتدفق الإنتاج',desc:'قيّم تخطيط الدفعات وثبات ملف التحميص والتبريد وتدفق التشغيل معاً عند الاستثمار في تحميص القهوة.',sections:[
    ['ميّز مصطلح البحث بدقة','قد تشير عبارة «آلة قهوة صناعية» أيضاً إلى معدات تحضير المشروبات. إذا كنت تبحث عن تحميص الحبوب، فحدّد «محمصة قهوة» ونظام الدفعات المطلوب. لا يتناول هذا الدليل اختيار آلات الإسبريسو أو التقديم.'],
    ['اربط هدف الدفعة بالإنتاج اليومي','تكتسب أوقات الإحماء والتحميص والتفريغ والتبريد وتبديل المنتج أهمية تماثل حجم الدفعة. اذكر هدفك على أنه إنتاج الحبوب المحمصة يومياً. ولا تستنتج طاقة الوردية من رقم دفعة واحدة.'],
    ['اسأل عن تكرار ملف التحميص','ينبغي أن يوضح المورد طريقة تسجيل الحرارة والوقت والإعدادات التي يمكن للمشغل تعديلها وكيفية تكرار الوصفة في الدفعة التالية. سجّل نوع الحبوب وظروفها الأولية أثناء التجربة.'],
    ['خطط للتبريد والعملية التالية','تعتمد خطوات التبريد والانتظار والطحن أو التعبئة بعد التحميص على استراتيجية المنتج. ينبغي التفكير في سرعة هذه المحطات ومساحتها مع اختيار المحمصة.'],
    ['تحقق من الملاءمة الفنية','يضم كتالوج سونوز ماكينة طراز تحميص القهوة HT 30. اطلب ورقة فنية حديثة وتجربة بحبوب ممثلة للتحقق من الطاقة ومصدر الحرارة وخيارات التحكم وملاءمة الموقع.']
  ]}
}
};
